### ISSUE TITLE
Upload single file does not fall on resolver

### ISSUE THREAD

**Issue by lucasdeassis** [jaydenseric/graphql-upload#114]
Hello, I'm trying to make a file upload from a mutation using `apollo-upload-client` and `apollo-upload-server`, but as I send the mutation the server does not respond on any available resolver and it seems that no errors are produced. Can someone help me? I tried following the example approach fro `jaydenseric` but my server is using `apollo-server-express`. Here are some depicts:

creating server:

```
const { ApolloServer } = require('apollo-server-express');
const { apolloUploadExpress } = require('apollo-upload-server');
const jwt = require('express-jwt');
const createGraphQLSchema = require('./graphql');

app.use(
    '/graphql',
    cors(),
    jwt({ secret, credentialsRequired: false }),
    apolloUploadExpress(),
  );

  const server = new ApolloServer({
    schema,
    context: ({ req }) => ({ user: req.user, db }),
  });

  server.applyMiddleware({ app });
```

executable schema

```
const glue = require('schemaglue');
const { makeExecutableSchema } = require('apollo-server-express');
const schemaDirectives = require('./directives');

const createSchema = async () => {
  const { schema, resolver } = glue('graphql/types');

  return makeExecutableSchema({
    typeDefs: schema,
    resolvers: resolver,
    schemaDirectives,
    formatError: () => new Error('Internal server error'),
  });
};
```
schema
```
scalar Upload

type Photo {
    id: ID!
}

type Mutation {
    uploadPhoto(file: Upload!, caption: String, isPrivate: Boolean): Photo
}

```

my resolver is more or less like:

```
(root,  { file, caption, private: isPrivate }, { user, db }) => { 
     const {
        createReadStream, filename, mimetype, encoding,
      } = await file;

      const imageStream = createReadStream();

      console.log('stream', imageStream);
      console.log('caption', caption);
      console.log('private', isPrivate);
} 
```

that is, configuring the apollo client like:

```
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { createUploadLink } from 'apollo-upload-client';

const apolloClient = new ApolloClient({
    cache: new InMemoryCache().restore({ }),
    createUploadLink({ uri: 'http://localhost:3001/graphql' }),
    ]),
});
```

Whenever I send the mutation, I see the request being sent and parsed, but in no way the request falls under the uploadPhoto resolver. Here is a console log of my resolver from `schemaglue`;

```
{ Mutation:
   { register: [AsyncFunction: register],
     login: [AsyncFunction: login],
     uploadPhoto: [Function: uploadPhoto],
     editPhoto: [AsyncFunction: editPhoto],
     deletePhoto: [AsyncFunction: deletePhoto] },
  Upload:
   { name: 'Upload',
     description: 'The `Upload` scalar type represents a file upload.',
     serialize: [Function: serialize],
     parseValue: [Function: parseValue],
     parseLiteral: [Function: parseLiteral],
     astNode: undefined,
     extensionASTNodes: undefined },
  Photo: { id: [Function: id], owner: [Function: owner] },
```

**Comment by jaydenseric** [comment]
Keep in mind that the current version of `apollo-server-express` [comes with a fork of this package at v5](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/package.json#L34) (current is v7.1.0), so there might be 2 things going wrong there.

1. The `apolloUploadExpress` middleware setup might be conflicting with the built-in setup.
2. `createReadStream()` is not available in the forked v5 version of `apollo-upload-server`, as [it was introduced in v7](https://github.com/jaydenseric/apollo-upload-server/blob/master/changelog.md#700).

**Comment by lucasdeassis** [comment]
@jaydenseric Thanks. Actually, it was the `apolloUploadExpress` conflicting with the built-in setup. I didn't know about that and couldn't find in the docs.

**Comment by semy** [comment]
Hello @jaydenseric ,

current version is 7.1 and apolloUploadExpress uses v5. But how can I use 7.1 without removing apolloUploadExpress? Is there an example somewhere?

Many thanks for your help :)

**Comment by jaydenseric** [comment]
The original question has been answered. @semy there is a lot of existing issues and discussions about that, really it is a question for the Apollo team... it is up to them to update their own dependencies and support users. You might like to follow https://github.com/jaydenseric/graphql-upload/issues/109.
