### ISSUE TITLE
Suggestion: use word "server" instead of word "API" in docs

### ISSUE THREAD

**Issue by koresar** [jaydenseric/graphql-upload#116]
Hello.

When I first used this module I couldn't find server side example implementation until @jaydenseric pointed me to it. Thanks!

The problem was and still is - the wording. The common way is "client + server", but in the modern multi-cloud worlds the people use "backend + frontend".

Whereas, the API stand for Application Programming Interface ([definition](https://www.google.com/search?q=define%3Aapi)). For example, every NPM module have an API. Operating systems have API. OS kernels have API. Every class/interface (as in OOP) have an API. Databases have API. Even the `graphql-upload` itself have own API.

Currently, in the README, the word API used interchangeable for the module API - https://github.com/jaydenseric/graphql-upload#api , and for the server side code - https://github.com/jaydenseric/graphql-upload#usage

I would like to supply a PR fixing that word misuse in the following repos:
* https://github.com/jaydenseric/graphql-upload
* https://github.com/jaydenseric/apollo-upload-client
* https://github.com/jaydenseric/apollo-upload-examples
* else?

How does that sound?

**Comment by jaydenseric** [comment]
In a best-practice setup, there are at least 4 environments:

- API (e.g. `https://api.foo.com`):
  - Server
  - Client
- App (e.g. `https://foo.com`):
  - Server
  - Client

Possibly more if you have multiple web (or native) apps using your organisation's API.

When referring to the "server", there are multiple meanings, same with "client".

For purposes of naming a repo, etc. it might be too narrow to call it the "GraphQL server", as it can also serve assets (`/uploads/user/asdf/xyz.png`), docs (`/graphiql`, or `/docs`), additional REST endpoints, etc. If you said "we can use the Github GraphQL server to power this feature" it would make less sense when talking to non GraphQL developers than saying "we can use the Github API …".

> See the example API and client.

This makes sense to me, as we are literally creating an example API for an example client.

Reworded to:

> See the example GraphQL server and client.

Sounds like you are referring to the server and client of one repo, as if the API and app share the same server. Also, "GraphQL server" is often interpreted as meaning the actual GraphQL server middleware (i.e.`apollo-server`, `express-graphql`, `graphql-api-koa`).

There might be some ambiguity currently, but I think it would take a fair bit of thought to fix to a level of semantic perfection, and I'm not as convinced that the current terminology is particularly confusing.

Happy to hear some specific suggestions though :)

**Comment by koresar** [comment]
The current terminology is very confusing and quite unique. In 20 years I can't remember anyone calling the server-side code as "API". Because everything in programming have API. :) Not just servers. But also clients, operating systems, your modules, etc.

Alternatives:
* backend
* server-side

If you make a (twitter?) poll and ask people's opinion among these there: "api", "backend", "server-side" I can assure you that "api" will be the last runner. :)
Can you?

**Comment by jaydenseric** [comment]
> I can't remember anyone calling the server-side code as "API".

I'm not talking about exclusively server-side code. The example API project involves API design (the schema) and potentially a full stack if GraphQL playground is being served too.

Yes, everything has an API. That why we qualify _which_ API we are referring to in a phrase:

> See **the example** API and client.

Perhaps clearer:

> See **the example GraphQL** API and web app.

See how GitHub uses the term "API": https://developer.github.com/v4

> … get you up and running with the GraphQL ***API*** …

> The spec determines the validity of the schema on the ***API*** server. The schema determines the validity of ***client*** calls.

> The ***API*** traverses and returns application data …

I don't think my usage here is out of the ordinary.

Again, I'm happy to review specific suggestions in specific places.

**Comment by koresar** [comment]
The GitHub page title is "GraphQL API v4" :) That's why there is no confusion.
The README of this module is referencing two different APIs. It's confusing.

Apollo is using the word Backend:
![image](https://user-images.githubusercontent.com/1622575/47128756-4fe85900-d2de-11e8-8379-5d5210cd994c.png)

When the use the word API they literally mean Application Interface, nothing backend related:
![image](https://user-images.githubusercontent.com/1622575/47128783-74dccc00-d2de-11e8-803a-65093eecd317.png)

Please, do the poll. Ask wider audience.

Cheers mate :)
