### ISSUE TITLE
Handle and reject parsing errors

### ISSUE THREAD

**Issue by edevil** [jaydenseric/graphql-upload#119]
I've noticed https://github.com/apollographql/apollo-upload-server/pull/2 which is a PR to a fork of this project that claims to fix a behaviour regarding handling of errors. Since the code mentioned is still present on this project I was wondering if this should be fixed here.

**Comment by mike-marcacci** [comment]
Hi @edevil, thanks for the note! This is [already handled here](https://github.com/jaydenseric/graphql-upload/blob/e2574456491445f24adc4e4f40ec3f3fdad01d36/src/processRequest.mjs#L326) along with a large number of other fixes and improvements.

**Comment by edevil** [comment]
@mike-marcacci Oh. A function called `exit` seems highly likely to kill the process, so I was tricked by the name. :)
