### ISSUE TITLE
Running tests without starting a server?

### ISSUE THREAD

**Issue by stringbeans** [jaydenseric/graphql-upload#121]
Hi!

I'm trying to write a test for a mutation that uses this GraphQLUpload type. Ideally I'd like to programmatically call graphql to test the mutation... 

```
const res = await graphql(schema, query, null, context)
```

Is this possible with uploads? Or do I have to actually start a server and post the file? 

Thanks in advance!

**Comment by mike-marcacci** [comment]
Hi @stringbeans, this is a great idea. While I personally do test against a full-blown HTTP server, this is definitely possible. You'll essentially be replicating [these lines](https://github.com/jaydenseric/graphql-upload/blob/e0ff3d09018ef9d725850643c278a51a9ae03765/src/processRequest.mjs#L271).

You can create an instance of [`fs-capacitor`](https://github.com/mike-marcacci/fs-capacitor), and pipe it the contents of your test file using `fs.createReadStream("somefile. Then set the value of the `GraphQLUpload` field in your request variables:

```js
const capacitor = new FSCapacitor()

fs
  .createReadStream("SomeTestFile.jpg")
  .pipe(capacitor)

variables.someUpload = Promise.resolve({
  filename: "SomeTestFile.jpg",
  mimetype: "image/jpeg",
  encoding: "binary",
  createReadStream() {
    const error = capacitor.error
    if (error) throw error
    return capacitor.createReadStream()
  }
})
```

**Comment by stringbeans** [comment]
this is great! thanks @mike-marcacci
