### ISSUE TITLE
How to test/simulate file upload from nodeJs unit/integration test?

### ISSUE THREAD

**Issue by DHFW** [jaydenseric/graphql-upload#125]
I would like to test my GraphQL endpoint, for that I created a test client based on `request-promise-native`. This works for all mutations, but not when it has an Upload type. I studied the unit testing code in this library, but could not figure it out.

I want to programatically upload a file and send it with form data. My current solution always has a file value of null on the receiving side.

Preparing the file for formData:
```
const file: any = fs.createReadStream('./a.txt');
const f = Promise.resolve({
      stream: file,
      filename: 'a.txt',
      mimetype: 'application/pdf',
      encoding: '7bit',
    });
```

In my formData (the `query` and `variables` are inserted before, but that is not the problem
```
const formData: any = {
      operations: `{ "query": "${query}", ${variables} }`,
      map: '{ "file0": ["variables.file"] }',
      file0: {
        value: f,
        options: {
          filename: 'a.txt',
          contentType: 'application/txt',
        },
      },
    };
```

Please help!

**Comment by jaydenseric** [comment]
You can find inspiration in the tests: https://github.com/jaydenseric/graphql-upload/blob/8d0f3e5ad144ab15eb7449e53322627eaed1d541/src/test.mjs#L77

You should only need [`node-fetch`](https://npm.im/node-fetch) and [`form-data`](https://npm.im/form-data):

```js
const FormData = require('form-data')
const fetch = require('node-fetch')

const body = new FormData()

body.append(
  'operations',
  JSON.stringify({
    query: /* GraphQL */ `
      mutation($file: Upload!) {
        uploadFile(file: $file) {
          id
        }
      }
    `,
    variables: {
      file: null
    }
  })
)
body.append('map', JSON.stringify({ 1: ['variables.file'] }))
body.append('1', 'a', { filename: 'a.txt' })

const response = fetch('http://localhost:3001', { method: 'POST', body })
```

I find it easier to create files in the test itself rather than use `fs`:

```diff
- body.append('1', 'a', { filename: 'a.txt' })
+ body.append('1', fs.createReadStream('./a.txt'))
```

**Comment by dionnyprensa** [comment]
How can I integrate with supertest?
We already have the tests of almost everything and I can't change the stack: Supertest, Mocha and Chai.

**Comment by jaydenseric** [comment]
@dionnyprensa I don't know off the top of my head, I don't use it. Is there a reason you can't?

**Comment by awilderink** [comment]
@dionnyprensa I created a little helper for this to use in my tests: 

```typescript
import { contentType } from 'mime-types'
import { extname } from 'path';
import app from '@/app'
import * as supertest from 'supertest'

const graphql = (query: string, variables: { [x: string]: any } = {}) => {
  const map = Object.assign({}, Object.keys(variables).map(key => [`variables.${key}`]));
  const request = supertest(app)
    .post('/graphql')
    .field('operations', JSON.stringify({ query }))
    .field('map', JSON.stringify(map));

  Object.values(variables).forEach((value, i) => {
    if (contentType(extname(value))) {
      request.attach(`${i}`, value);
    } else {
      request.field(`${i}`, value);
    }
  });

  return request;
};

```

```typescript
describe('Upload', () => {
  it('should return a file after uploading one', async done => {
    const res = await graphql(
      /* GraphQL */ `
        mutation($file: Upload!) {
          singleFileUpload(file: $file) {
            id
          }
        }
      `,
      { file: __dirname + '/__files/image.jpg' }
    )
    expect(res.body.data.singleFileUpload.id).toBeDefined()
    done()
  })
})

```

I use it together with apollo-server-express and Jest, but I think it might work for you aswell. It may even work with regular queries, but I haven't tested that yet.

**Comment by dionnyprensa** [comment]
> @dionnyprensa I don't know off the top of my head, I don't use it. Is there a reason you can't?

Hey
I'm sorry, I forgot to answer.

I'll be testing the @awilderink option later

**Comment by Constantini21** [comment]
> ```ts
> __dirname + '/__files/image.jpg'
> ```

hello what would be an app in supertest(app)?

**Comment by steinroe** [comment]
I found this approach very helpful and lean, especially when working with the apollo test client:

```

        const filename = `some-powerpoint.pptx`
        const file = fs.createReadStream(resolve(`./tests/${filename}`))

        const QUERY = `
          mutation addFile($file: Upload!) {
            addFile(file: $file) {
              id
            }
          }
        `

        const d = await client.mutate({
            query: QUERY,
            variables: {
                file: new Promise(resolve => resolve({
                    createReadStream: () => file,
                    stream: file,
                    filename: filename,
                    mimetype: `application/vnd.openxmlformats-officedocument.presentationml.presentation`,
                })),
            },
        })

```

To be found [here](https://medium.com/@semur.nabiev/unit-test-file-uploads-in-your-apollo-graphql-server-766c7d07a605).

**Comment by XshubhamX** [comment]
Can you tell what I am doing wrong, Test is giving error file is missing 

const axios = require('axios');
const { URL } = require('../constants');
const path = require('path');
const fs = require('fs');

const uploadBody = async (body) => {
  const json = await axios.post(URL, body,{
    header
  });
  return json;
};

describe('image upload', () => {
  test('signup test', async () => {
    const body = new FormData();

    body.append(
      'operations',
      JSON.stringify({
        query: `
        mutation ($file: Upload!) {
          signUp (data:{
            email:"user1011@gmail.com",
            firstName:"user_fname",
            lastName:"user_lname",
            password:"Password1234",
          }, file: $file){
            user{
              image
            }
          }
        }
        `,
        variables: {
          file: null,
        },
      })
    );

    const file_name = 'logo.png';
    body.append(
      'map',
      JSON.stringify({
        1: ['variables.file'],
      })
    );
    body.append('1', fs.createReadStream(path.resolve(__dirname, `./test_image/${file_name}`)));
    const { data } = await uploadBody(body);
    expect(data.errors).toBe(null);
  });
});

**Comment by XshubhamX** [comment]
@jaydenseric  Please have a look at my code

**Comment by jaydenseric** [comment]
@XshubhamX only share properly formatted and syntax highlighted code on GitHub:

https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting

Doing so really improves the quality of life of everyone reading such code all day, every day. Please edit your comment to fix it up for the hundreds of people who will come along and read it.

Also, in future don't beg in multiple [comments](https://github.com/jaydenseric/graphql-upload/issues/125#issuecomment-814383286) for people to help you do you own work. There are [16 watchers](https://github.com/jaydenseric/graphql-upload/watchers) of this repo, so your 2 comments resulted in 16 x 2 = 32 (+ 5 other participants of this issue x 2, + other people subscribed to this issue x 2) email notifications to busy people that they have to read and clear.

Most package authors enjoy helping people who are courteous, communicate clearly, and are asking a technical question specifically about the author's package that is not answerable by reading docs or googling how to use standard web APIs, and has not been asked before in past issues. Most maintainers refuse to help their millions of users write or debug their project code, especially when their problems relate to unrelated software.

At first glance your `FormData` field structure looks ok. As I already [commented years ago in this thread](https://github.com/jaydenseric/graphql-upload/issues/125#issuecomment-440853538), in my own tests I try to stick to native/standard web APIs as close as possible, and use `fetch` and `FormData` polyfills for Node.js that work well together. Probably whatever `FormData` polyfill you're using doesn't convert a Node.js FS read stream into a file field when using `append`, or `axios.post` is not noticing the body is a `FormData` instance to send a multipart request.

**Comment by XshubhamX** [comment]
Thak you sir.I will keep our point in mind

**Comment by CarlosBalladares** [comment]
if anyone is wondering  how test uploads is version "8.0.11"  or some nearby version 
```ts

    import { Upload, FileUpload } from "graphql-upload";
    //.... unrelated code
    const file = fs.createReadStream(path.resolve(__dirname, "./somefileinyourtests.txt"));
    
    // this is the valid input object it is expecting.
    const upload = new Upload();
    const fileUpload: FileUpload = {
      filename,
      mimetype,
      encoding: "test",
      createReadStream: () => file,
    };
    upload.promise = new Promise((r) => r(fileUpload));
    upload.file = fileUpload;

    const res = await graphql({
      schema,
      source: `
        mutation SingleUpload($file: Upload!) {
          singleUpload(file: $file) {
            code
            filename
          }
        }
        `,
      variableValues: {
        // mock the file value graphql-upload
        file: upload,
      },
      // here whatever your context is
      contextValue: testContext,
    });
```
