### ISSUE TITLE
Errors in tests appearing for Node.js >= v10.14.2

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/graphql-upload#130]
[Something that changed between Node.js v10.14.1 and v10.14.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.14.2) has caused errors to log in a few places in tests (which still pass):

https://travis-ci.org/jaydenseric/graphql-upload/jobs/477605581#L570

```
Error: Parse Error
      at socketOnEnd (_http_server.js:455:20)
      at Socket.emit (events.js:193:15)
      at Socket.EventEmitter.emit (domain.js:459:23)
      at endReadableNT (_stream_readable.js:1129:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

We need to work out if its a bug in Node.js,  or a `graphql-upload` compatibility issue with the new Node.js versions.

**Comment by jaydenseric** [comment]
These Node.js changes may be related?

* [[`cb861a4897`](https://github.com/nodejs/node/commit/cb861a4897)] - **stream**: do not error async iterators on destroy(null) (Matteo Collina) [#23901](https://github.com/nodejs/node/pull/23901)
* [[`6f4a638175`](https://github.com/nodejs/node/commit/6f4a638175)] - **stream**: ended streams should resolve the async iteration (Matteo Collina) [#23901](https://github.com/nodejs/node/pull/23901)
* [[`ce79ae6544`](https://github.com/nodejs/node/commit/ce79ae6544)] - **stream**: async iteration should work with destroyed stream (Matteo Collina) [#23785](https://github.com/nodejs/node/pull/23785)

**Comment by mike-marcacci** [comment]
Just looking at changes in node, [this](https://github.com/nodejs/node/commit/ff7d053ae6b7f620516049e5c9bd1b6ab348835f#diff-feaf3339998a19f0baf3f82414762c22) may be related. I think the first thing to do is figure out where these are being logged. I do remember having to wrestle tap at one point to keep it from logging expected errors, so this may be something like an unhandled `error` event or `Promise` rejection that tap is helpfully bringing to our attention.

The actual error that is logged is not surprising to see, as we *are* aborting the request in those tests. I know that between node 8, 9, and 10, errors would appear in the stream's pieces in different orders, so we already have logic that covers a broad range of timings. My initial suspicion is that node made a very subtle change, and we know about (and handle) an error from before attaching an error handler to a downstream piece previously wasn't propagated the error, but now is.
