### ISSUE TITLE
Usage of graphql upload

### ISSUE THREAD

**Issue by bluedusk** [jaydenseric/graphql-upload#136]
Hi guys,

I am able to upload file to graphql server built with apollo-sever-lambda without graphql-upload.
I am using apollo-upload-client for apollo client setup.
I am confused when will I need this graphql-upload library ? 

Many Thanks.

**Comment by jaydenseric** [comment]
Apollo Server installs and uses `graphql-upload` automatically, so no need to manually install it if you are using Apollo Server :)
