### ISSUE TITLE
why a uploaded file via sftp (filezilla) to google cloud is empty?

### ISSUE THREAD

**Issue by jpedro90** [jaydenseric/graphql-upload#140]
I'm trying to upload the wp-config.php to google cloud via sftp filezilla but when i do this the file uploaded is completely empty in the server.

I've tried already with other ftp clients (WinSCP) and disabled my firewall but still have the same problem.

also changed the permissions to 777 before i upload the file. I removed some files (images) because i was thinking that the problem was the space on the disk but still have the same problems.

Can someone help me with this?

**Comment by jaydenseric** [comment]
@jpedro90 suspiciously your account was created today, and this is your first issue. This repo has nothing to do with PHP, FTP or FileZilla, so I have to assume your some sort of spam bot or experiment.

**Comment by jpedro90** [comment]
No, I'm not a bot. I'm quite new in this area but i want to learn. That's why I'm here. Can you help me?

**Comment by jaydenseric** [comment]
Can you try to explain better what your issue has to do with this repo?
