### ISSUE TITLE
Batching operations (array) returns BadRequestError

### ISSUE THREAD

**Issue by rlux** [jaydenseric/graphql-upload#142]
When using an array inside the operations field, I always get this error:
BadRequestError: Invalid type for the ‘operations’ multipart field

I used the example query from here https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request-2

When using a single object instead of an array, it works.

Looking into the source code, I found the check isObject(operations). This seems to return false for arrays. Please also allow arrays in that type check!

**Comment by jaydenseric** [comment]
Oof, if that happening it's certainly not meant to! Let's add a test and fix it.

**Comment by jaydenseric** [comment]
Fix published in [v8.0.6](https://github.com/jaydenseric/graphql-upload/releases/tag/v8.0.6) 🚀
