### ISSUE TITLE
Usage with apollo-server-express and makeExecutableSchema

### ISSUE THREAD

**Issue by ScreamZ** [jaydenseric/graphql-upload#145]
Hello,

In order to use `graphql-shield` I've been forced to switch to `makeExecutableSchema`, seems like the built-in apollo-upload in no longer working here ? Should I have to add  the library manually in resolver and scalar definition ?

Here is my code

```ts
import { ApolloServer } from "apollo-server-express";
import express from "express";
import { applyMiddleware } from "graphql-middleware";

import Permissions from "./modules/authentication/permissions";
// …

// Build schema with middleware
  const schema = applyMiddleware(
    makeExecutableSchema({
      resolvers
      typeDefs
    }),
    Permissions,
  );

  // Init server
  const apolloServer = new ApolloServer({
    context: () => {},
    schema,
  });

  // Start server
  const app = express();
  apolloServer.applyMiddleware({
    app,
    path: "/",
  });
// …
```

And i get `(node:7545) UnhandledPromiseRejectionWarning: Error: Unknown type "Upload". Did you mean "Float"?`

Best regards

**Comment by jaydenseric** [comment]
Those questions relate more to Apollo products than this package. If I knew the answers off the top of my head I would help you out, but I think you might need to ask around in the [Apollo Spectrum](https://spectrum.chat/apollo) or raise an issue in one of their repos if you think there might be a bug in their implementation :)

**Comment by giovangonzalez** [comment]
Hi @ScreamZ 
I'm in the same situation, did you solved it?

**Comment by jaydenseric** [comment]
@giovangonzalez [in the Apollo Server docs](https://www.apollographql.com/docs/apollo-server/features/file-uploads/):

> If you create your schema with makeExecutableSchema and pass it to ApolloServer constructor using the schema param, make sure to include `Upload` scalar.

**Comment by ScreamZ** [comment]
You have to re-implement it on your own, just declare the Scalar and give the resolver for it using the one which is shipped with apollo-upload.
