### ISSUE TITLE
Need to forward a multipart request with Graphql Express

### ISSUE THREAD

**Issue by MeiyazhaganSelvam** [jaydenseric/graphql-upload#146]
Used the graphql-express for making a graphql server for two remote stiched schemas, on mutation request the graphqlHTTP was sending only query and variables. The file part is null. Need to forward the multipart request from the merged schema to actual schema using graphql express

**Comment by mike-marcacci** [comment]
Hi @MeiyazhaganSelvam, this package simply supplies parsed file streams in the request, and doesn't have anything to do with the resolvers. If you're using a tool like Apollo's `mergeSchemas` to automatically generate resolvers, you'll need to open an issue there asking them to forward requests according to the [GraphQL Multipart Request spec](https://github.com/jaydenseric/graphql-multipart-request-spec).
