### ISSUE TITLE
How to upload from graphiql?

### ISSUE THREAD

**Issue by teknolojia** [jaydenseric/graphql-upload#147]
Can use this from graphiql? If so how? I am using express-graphql

**Comment by jaydenseric** [comment]
GraphiQL doesn't support file uploads yet, but [Altair](https://altair.sirmuel.design) does! See [this article](https://sirmuel.design/working-with-file-uploads-using-altair-graphql-d2f86dc8261f). GraphQL Playground has [an issue for it](https://github.com/prisma/graphql-playground/issues/597), but no progress yet.

Like explained in [this comment](https://github.com/prisma/graphql-playground/issues/597#issuecomment-439746204), there are also a few ways to manually construct and send GraphQL multipart requests.

**Comment by teknolojia** [comment]
@jaydenseric Thanks for detail responce
