### ISSUE TITLE
createReadStream is not a function

### ISSUE THREAD

**Issue by harysonii** [jaydenseric/graphql-upload#148]
I am trying to upload an image to my express-graphql server. I am using the graphql-upload on the server and graphql and graphql-tag on the client.

server
`addProfilePic: {
      type: UserImageType,
      args: {
        image: { type: GraphQLUpload }
      },
      resolve: async (parent, args) => {
        console.log(args.image)
        const { filename, mimetype, createReadStream } = await args.image;
        const stream = await createReadStream()
        console.log(stream)

        /* parser(req, res, function (err) {
           if (err) return next(err)
           console.log(res)
           // use `req.file` here
         })*/

      }
    }`

client
` const uploadProfile = async (e) => {
    e.preventDefault()

    const requestBody = gql`
            mutation addProfilePic($image: Upload) {
                addProfilePic(image: $image)
                {
                     id
                 }
            }
            
    `

    axios.post("http://localhost:4000/", {
      query: print(requestBody),
      variables: {
        image: picture // picture
      },
    })
      .then(res => {
        if (res.status !== 200 && res.status !== 201) {
          throw new Error("Failed");
        }
        console.log(res)
        //return res.json();
      })/*.then(resData => {
            console.log(resData);
          })*/
      .catch(err => {
        console.log(err)
      });
  }`

**Comment by jaydenseric** [comment]
In the future, can you please submit tidier code examples? The formatting is terrible, and there are redundant commented out bits.

`axios.post()` won't send a [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec), that is your issue.

**Comment by harysonii** [comment]
I was able to use Apollo-client-upload. Thank you
