### ISSUE TITLE
Module '"graphql-upload"' has no exported member 

### ISSUE THREAD

**Issue by rico345100** [jaydenseric/graphql-upload#150]
This line of code:

```javascript
import { graphqlUploadExpress } from 'graphql-upload';
```

Gives me this error:

> Module '"graphql-upload"' has no exported member 'graphqlUploadExpress'.ts(2305)

I'm using apollo-server-express and above error occurs. So I re-tried after install graphql-upload but still have same error message. Installing @types/graphql-upload doesn't help either.

Using apollo-server@2.6.1 and apollo-server-express@2.6.1.

**Comment by jaydenseric** [comment]
I don't know why you're attempting to import the middleware as you don't need to setup `graphql-upload` for Apollo Server, it comes built in. Chances are you don't need to worry?

Regardless, this seems to be an issue you are having with Apollo Server and TypeScript, neither of which are in the scope of this repo.

**Comment by mike-marcacci** [comment]
Hey @rico345100 - I'm the author of the types, [which live in the DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/graphql-upload). I suspect you have something configured strangely with your TS config.

As @jaydenseric mentioned, you probably don't want to be importing this at all, but if you do and continue to run into this, reopen this issue in DefinitelyTyped and tag me in it.
