### ISSUE TITLE
Do I *have* to consume every stream?

### ISSUE THREAD

**Issue by juona** [jaydenseric/graphql-upload#151]
Hey there,

Thank you for the package and apologies for asking this - I have looked through the past issues and found a few related threads and a pull request but was not able to extract a decisive answer to my question, so here goes.

When uploading two files in one request, the _second_ file promise will only resolve once the stream of the first one is consumed, correct? By "_second_" I mean whichever is processed later, so to speak. So if I do not consume the stream, my request will hang, and I must at least call `.resume()` to avoid this?

**Comment by mike-marcacci** [comment]
Hi @juona – definitely don't apologize for asking a great question! @jaydenseric and I spent a _huge_ amount of time getting this right.

There's a two-part answer here:

1. No, you don't have to _consume_ each stream in your app code, and you don't have to worry about the order. We build and use [fs-capacitor](https://github.com/mike-marcacci/fs-capacitor) for this purpose. It buffers the upload to the filesystem (while allowing synchronized read/write), so that you can consume uploads "out of order", and can begin consuming the same upload multiple times (such as when using the same variable twice).
2. However, whenever you do create a read stream from a resolved upload promise (using its `createReadStream()` method), you will need to either fully consume this stream, or `.destroy()` it.

Hope that helps!

**Comment by juona** [comment]
Thank you for the answer, it does help a bit. Yet somehow the behaviour seems to be different with graphql-upload 8.0.6 on Express, but there might be something that I am missing. It is actually behaving quite differently. If/when I make a reproducible example, I will let you know!

**Comment by mike-marcacci** [comment]
@juona that's very interesting. Please do; if there's something wrong, we definitely want to know. If you do want to create a minimal reproduction, [the tests](https://github.com/jaydenseric/graphql-upload/blob/master/src/test.mjs) run through just about every conceivable scenario in both Koa and Express, so you should be able to find a similar scenario as a starting point. A PR with a new failing test is always welcome!

**Comment by juona** [comment]
My bad, I had the wrong version, apparently. Thank you for your quick support!

**Comment by mike-marcacci** [comment]
Absolutely; glad to hear you got it fixed.

**Comment by juona** [comment]
Okay, so now my setup is this:

**graphql-upload 8.0.6**
**apollo-server-express 2.0.5** (a bit old; I have my reasons but there's a chance that the problem lies in Apollo somehow)

There's still some odd behaviour, which I assume to be related to the original question.

Here's my mutation schema:

```graphql
testUploads(uploads: [Upload]): Boolean
```

And here's the resolver:

```javascript
testUploads: (_, { uploads }) => {
  console.log("Mutation called");

  return Promise.all([
    uploads[0].then(file => {
      console.log("Upload 0 resolved");
      const stream = file.createReadStream();
      stream.resume(); // LINE 1
    }),
    uploads[1].then(file => {
      console.log("Upload 1 resolved");
      const stream = file.createReadStream();
      stream.resume(); // LINE 2
    })
  ]).then(() => true);
}
```

I am calling this code via the Insomnia client, using a manually formed multipart request:

```json
{
  "operationName": null,
  "variables": { "uploads": [null, null] },
  "query": "mutation ($uploads: [Upload]) {  testUploads(uploads: $uploads)  }"
}

{ "0": ["variables.uploads.0"], "1": ["variables.uploads.1"] }
```

I am uploading two different files, their sizes do not seem to have any influence over this.

Here's the odd behaviour:

It does not matter what I have in **LINE 1** - could be `stream.resume()`, `stream.destroy()`, a `stream.pipe(process.stdout)`, or it could be commented out (i.e. a stream is created via `createReadStream()` but nothing is ever done with it!), this has no influence to how the code works.

Now, **LINE 2** can also be just about anything - a `stream.resume()`, `stream.pipe(process.stdout)`, or commented out. Whatever the combination of **LINE 1** and **LINE 2**, the code works fine, i.e. the mutation gets called each time, the uploads resolve and I get a response with the value **true**, as expected. I don't see any increase in the memory usage. Perhaps the unused uploads are piling up somewhere in the filesystem, but that's beyond my concerns.

There is one exception: if **LINE 2** is `stream.destroy()`, then this happens:

1) The first time I call the mutation everything seems to be working fine - both uploads resolve and I get my response.
2) However, the second time I call it, the request just hangs - it does not even reach my HTTP loggers. I suspect it doesn't even hit Express itself, so not sure what is actually going on.
3) Here's the fun part. If I cancel the request and then fire another one - it works okay again.
4) If I then fire a fourth request, you guessed it - it hangs.

From hereon, every other request succeeds, and every other hangs.

The behaviour seems to somewhat defy both of your previous statements because:

1) The bug only manifests itself when I use `stream.destroy()` on the _second_ upload, so in some way the order _does_ matter.
2) If I do nothing with both streams, there really is no problem, so it doesn't seem like I have to do anything with the streams at all, even after they have been created via `createReadStream()`.
