### ISSUE TITLE
Error when uploading 900+ files in one request

### ISSUE THREAD

**Issue by yummyummyummy** [jaydenseric/graphql-upload#153]
```TSX
async (_, { files, projectId }, ctx) => {
        const slicedFiles: any = [];
        const chunkSize = 100;
        for (let index = 0; index < files.file.length; index += chunkSize) {
          slicedFiles.push(files.file.slice(index, index + chunkSize));
        }

        const createPromise = async (uploads: any, ctx: any) => {
          const promises = uploads.map((upload: any) => {
            const { file, filetype, participant, scene, trial } = upload;
            return new Promise(resolve => {
              resolve(
                processUpload(
                  {
                    file,
                    filetype,
                    participant,
                    scene,
                    trial,
                    projectId,
                  },
                  ctx,
                ),
              );
            }).catch(err => {
              console.log(err);
            });
          });
          return await Promise.all(promises).then(() => {
            console.log('done');
          });
        };

        for (let i = 0; i < slicedFiles.length; i++) {
          await createPromise(slicedFiles[i], ctx);
        }

        return { test: 'finished' };
      },
```

this is my resolver for multiple files uploading. the processUpload functions is like this below.

```TSX
export const processUpload = async (file: any, ctx: any) => {
  if (!file) {
    return console.log('ERROR: No file received.');
  }

  const { filetype } = await file;
  const { createReadStream, filename, mimetype, encoding } = await file.file;

  const stream = createReadStream();

  const sceneInfo = await ctx.prisma.scenes(
    {
      where: {
        AND: [{ ... }, { ...}],
      },
    },
     { ... } ,
  );

 .......

  const key = '************';

  await s3
    .upload({
      Key: key,
      ACL: 'public-read',
      Body: stream,
      Bucket: 'some_bucket',
    })
    .promise();

  const data: FileCreateInput = {
    filename,
    mimetype,
    encoding,
  };

  const { id } = await ctx.prisma.createFile(data,  {... } );

  const fileInfo = {
    id,
    filename,
    mimetype,
    encoding,
  };

  return fileInfo;
};
```

when my resolver got message, and it runs 100 processUpload function parallel. I am testing with 1157 files and it works very well for 800~900 files and suddenly It returns error like below.

```Shell
Error: A ReadStream cannot be created from a destroyed WriteStream.
    at WriteStream.createReadStream (/***/node_modules/fs-capacitor/lib/index.js:188:31)
    at createReadStream (/***/node_modules/graphql-upload/lib/processRequest.js:237:28)
    at Object.<anonymous> (/***/server/fileUploader.ts:21:18)
    at Generator.next (<anonymous>)
    at fulfilled (/***/server/fileUploader.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

it works fine with chunkSize 500, but it returns same error while batching 15 ~ 16 loop.
Am I doing something wrong?

**Comment by yummyummyummy** [comment]
sorry, it also fails with chunkSize 500 in the last loop

**Comment by mike-marcacci** [comment]
Hi @yummyummyummy, I'm having a bit of trouble following this (I don't really see what the whole first code block is supposed to be doing), but I will say that this error occurs when `createReadStream` is called _after_ the resolvers have returned and the underlying resources have been cleaned up. Is there a chance the resolver is returning early?

**Comment by yummyummyummy** [comment]
Hi @mike-marcacci, the first code block is separating files array into chunks with size of chunkSize and then batching uploading files for each chunk. I mean, if I uploaded 1k files and if chunkSize is 100, it is going to reshape the array as [[...100 files...], [...100 files...], ... ] like this. Then it uploads each grouped files.

in the for-loop of first code block, it is waiting for all promises have finished. Then iterate next loop. I think resolvers never returned before the loop finished.

**Comment by mike-marcacci** [comment]
Hi @yummyummyummy, I'm sorry, but I'm still really struggling to follow this...

`slicedFiles` appears to be an array of byte chunks, each of which is then mapped into a variable called `upload`, which is then destructured as `const { file, filetype, participant, scene, trial } = upload;`. This obviously can't work, so perhaps this is where to start?

**Comment by mike-marcacci** [comment]
Aaah, I see; it's a resolver expecting a `files` object, each of which has a `file: Upload` field.

In this case, you aren't ever waiting for the `file` promise to resolve; make your map function `async` and:

```js
const { file, filetype, participant, scene, trial } = await upload;
```

**Comment by yummyummyummy** [comment]
I am sorry make you confused. 
```TSX
const { file, filetype, participant, scene, trial } = await upload;
```
For this line, file is Upload type and all the other things are just strings.

The resolver takes `{files: {file: Upload, filetype: string, participant: string ... }[], projectId: string}` as input.

I named **files** as `Upload` and each struct `{file: Upload, filetype: string ... }` as `upload` in code.

**Comment by jaydenseric** [comment]
Hi @yummyummyummy, did you solve your problem?

**Comment by yummyummyummy** [comment]
No, but instead of uploading 1000+ files, I am uploading just 1 compressed .zip file and it works.

**Comment by jaydenseric** [comment]
@yummyummyummy glad you figured out a workaround :)

Thanks for the report, but the shared code is a little complicated to follow and there are a lot of things that could be going wrong, so if you would like to help investigate further the next step would be to create a very minimal project reproducing the issue. At that time, we can confirm a bug exists either here or in `fs-capacitor`.

If other people experience a similar issue we can reopen.

**Comment by Mikhailosev** [comment]
Fot me this happened when i immediately cancelled file upload on frontend, so i have to make e.preventDefault, but it is also possible with some other  upload methods, it seems to me that this error happens when the host that sends files for upload terminates the connection somehow
