### ISSUE TITLE
File object is empty when using apollo federation

### ISSUE THREAD

**Issue by lichri11** [jaydenseric/graphql-upload#157]
After federating a service that implements the upload scalar, for some reason, if I hit that resolver from the federated gateway, the file object is empty.

```
(base) cL:gateway chris$ npm run start-apollos

> bx-gateway@1.0.0 start-apollos /Users/chris/projects/bx/gateway
> concurrently "npm:start-apollo-*"

[start-apollo-data]
[start-apollo-data] > bx-gateway@1.0.0 start-apollo-data /Users/chris/projects/bx/gateway
[start-apollo-data] > NODE_ENV=development node -r ts-node/register ./src/apollos/DataLibrary/index.ts
[start-apollo-data]
[start-apollo-accounts]
[start-apollo-accounts] > bx-gateway@1.0.0 start-apollo-accounts /Users/chris/projects/bx/gateway
[start-apollo-accounts] > node -r ts-node/register ./src/apollos/Accounts/index.ts
[start-apollo-accounts]
[start-apollo-bioref]
[start-apollo-bioref] > bx-gateway@1.0.0 start-apollo-bioref /Users/chris/projects/bx/gateway
[start-apollo-bioref] > node -r ts-node/register ./src/apollos/BioRef/index.ts
[start-apollo-bioref]
[start-apollo-accounts] Account apollo running at http://localhost:9001/
[start-apollo-bioref] BioRef Apollo running at http://localhost:9003/
[start-apollo-data] 🚀 Server ready at http://localhost:9002/graphql
[start-apollo-data] { file: {}, something: 'hello' }
[start-apollo-data] { file: {}, something: 'hello' }
```

But then if I hit the service directly, everything is fine.
```
[start-apollo-data] 🚀 Server ready at http://localhost:9002/graphql
[start-apollo-data] Promise {
[start-apollo-data]   { filename: 'test.csv',
[start-apollo-data]     mimetype: 'text/csv',
[start-apollo-data]     encoding: '7bit',
[start-apollo-data]     createReadStream: [Function: createReadStream] } }
```
Is there something I am doing wrong with the apollo-gateway?

For reference,

```
// TypeDefs
export const typeDefs = gql`
  scalar Upload

  extend type Mutation {
    testUpload(file: Upload, something: String): String
  }
`;
// *Resolvers

import { GraphQLUpload } from 'graphql-upload';

const testUpload = async (obj, { file }, ctx, info) => {
  const { createReadStream } = await file;
  console.log(file);
  return '';
};
export const resolvers = {
  Upload: GraphQLUpload,
  Mutation: {
     testUpload(obj, args, ctx, info) {
        return testUpload(obj, args, ctx, info)
     }
  },
};

```
For now, I've worked around it by registering another client that directly hits the service instead of the gateway just to do file uploads, but I feel like this defeats the point of federating in the first place.

Any suggestions/guidance would be greatly appreciated!

**Comment by jaydenseric** [comment]
> For now, I've worked around it by registering another client that directly hits the service instead of the gateway just to do file uploads, but I feel like this defeats the point of federating in the first place.

I hear you. Unfortunately there is nothing I can do about it from here; it is really up to Apollo to support their customers by implementing features or offering workarounds. I don't think you can use subscriptions with Apollo Federation either.

**Comment by lichri11** [comment]
Thanks @jaydenseric 
I've posted this issue on the apollo-server repo. Hopefully they will be able to fix it!

**Comment by galbanese91** [comment]
Hi @lichri11, I am having trouble uploading an image file when i hit the service directly instead of hitting my federated gateway. I have a seperate ApolloClient that includes the 'createUploadLink'. I keep hitting the error:

**BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).**

Do you have any idea what that may be?

**Comment by edelreal** [comment]
@lichri11 thanks for filing the apollo-server issue!

Adding a link here for reference: https://github.com/apollographql/apollo-server/issues/3033

**Comment by mouhsinelonly** [comment]
Is there any updates concerning  this issue

**Comment by mike-marcacci** [comment]
@mouhsinelonly Federation is an apollo thing, and you can follow the link in [the previous comment](https://github.com/jaydenseric/graphql-upload/issues/157#issuecomment-539578131) if you want to follow along.

**Comment by mouhsinelonly** [comment]
thank you
