### ISSUE TITLE
Exceeding maxFieldSize generates unhelpful error message

### ISSUE THREAD

**Issue by sgehrman** [jaydenseric/graphql-upload#159]
I've noticed that some jpgs I upload, I get this error:
BadRequestError: Invalid JSON in the ‘operations’ multipart field (https://github.com/jaydenseric/graphql-multipart-request-spec).

Some jpgs work fine, also noticed gifs give the same error.

**Comment by sgehrman** [comment]
After googling for a few hours, I figured it out.  The docs aren't great.

const fileUploadOptions = {
    maxFieldSize: 1024 * 1024 * 10
  };

 const server = new ApolloServer({
    uploads: fileUploadOptions
  });

**Comment by JacobT14** [comment]
I've been running into this all morning and still haven't gotten around this.  I've followed the docs for setting up, and tried your suggestion here, but no luck.

Anybody else have any other ideas?  I

**Comment by mike-marcacci** [comment]
@sgehrman - thanks for the report. Not sure how I missed this (my GitHub notifications have been having problems). This sounds like a bug in the sense that the error message is incorrect, even if the behavior (error if the field is too large) is correct.

@JacobT14 there are essentially 2 possibilities:
1. The request is in fact invalid.
2. You are hitting the max field size. It looks like we have a poor error message, but the actual behavior is correct. To eliminate this as a possibility, set `maxFieldSize` to `Infinity`.
