### ISSUE TITLE
spread operator added to graphqlUploadKoa in 8.1.0 breaks webpack

### ISSUE THREAD

**Issue by tehjape** [jaydenseric/graphql-upload#163]
webpack won't bundle the [spread operator](https://github.com/jaydenseric/graphql-upload/blob/master/src/graphqlUploadKoa.mjs#L33) and the babel plugins don't apply to the node_module files, so we end up getting
```
ERROR in ./node_modules/graphql-upload/lib/graphqlUploadKoa.js
Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
| const graphqlUploadKoa = ({
|   processRequest = _processRequest.processRequest,
|   ...processRequestOptions
| } = {}) => async (ctx, next) => {
|   if (!ctx.request.is('multipart/form-data')) return next()
```

**Comment by jaydenseric** [comment]
This code is only intended to work in a Node.js server environment, where the spread syntax is natively supported.

Modern `webpack` versions should be able to handle the syntax, perhaps check if you have up to date `webpack` and `acorn` versions? [`acorn@5.4.0`](https://github.com/acornjs/acorn/blob/5.7.3/CHANGELOG.md#540-2018-02-01) supports it:

https://github.com/acornjs/acorn/blob/master/acorn/CHANGELOG.md#540-2018-02-01

**Comment by mike-marcacci** [comment]
As @jaydenseric mentioned, the spread operator works in the engines we support:

https://github.com/jaydenseric/graphql-upload/blob/2223e7a565532d831367d5ea0b5970954eb7b5f2/package.json#L32-L34

I'm going to go ahead and close this, as I'm fairly confident this isn't actually a bug. However, feel free to continue explaining your use case here comments, and I'd be happy to help as I have time.
