### ISSUE TITLE
CORS errror when uploading a file exceeding the limit

### ISSUE THREAD

**Issue by francoisromain** [jaydenseric/graphql-upload#165]
Hello and thank you for your great work on this library. 

I use it 
- with express-graphql on the server 
- with vuejs on the client (with graphql-upload-client). 

Everything works fine except one thing: 
- if we try to upload a file exceeding the limit defined by `maxFileSize` the error message on `localhost` is correct: `File truncated as it exceeds the 3000000 byte size limit.`. But when I do the same on a remote VPS, the error is 

```
POST https://api.my-app.tld/ 413
Access to XMLHttpRequest at 'https://api.my-app.tld/' from origin 'https://my-app.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I tried to set the CORS `Access-Control-Allow-Origin` on the server to different values (including '*'), with no success. 

Why is this error message different from `localhost`? 
How to control this error message?

Thank you

* * *

The repos are here: 
- api: https://github.com/MTES-MCT/camino-api/blob/80ed1de9bd50b70ded6438feca063e7ba8b3c154/src/server/middleware-upload.ts
- ui: https://github.com/MTES-MCT/camino-ui/blob/f4b6d745e2aa3e45d5037c1369183c5eb9c1ce4e/src/api/_graphql-client.js#L38

**Comment by torontochen** [comment]
I got the same problem before, try this,

server.applyMiddleware({
  app,
   bodyParserConfig: {
    limit: "50mb"
  }
})

**Comment by mike-marcacci** [comment]
Hi @francoisromain, this is indeed very interesting. There is no difference between the behavior on localhost and your production system; the latter is simply hosted on a different domain, hence the CORS error.

However, what's strange to me is that there is a difference in CORS behavior between success and failure responses. Can you confirm that this is in fact the case?

**Comment by francoisromain** [comment]
Thank you for your answers.

@torontochen `server.applyMiddleware` looks like an apolloGraphQL server thing, but I use [express-graphQL](https://github.com/graphql/express-graphql). I am going to see if I can do something like that with `express-body-parser`.

@mike-marcacci 
On localhost, 
- the client is at `http://localhost:8080` 
- the api is at `http://localhost:4000`. 

On the production environment, 
- the client is hosted at `https://my-app.tld` 
- the api is at `https://api.my-app.tld`. 

**Upload works fine in both environments** if the uploaded files are under the `maxFileSize`. 
**If the file size exceed this limit**, the error is different in each environment: 
- the error on localhost: `File truncated as it exceeds the 3000000 byte size limit.`
- the error in production: `Access to XMLHttpRequest at 'https://api.my-app.tld/' from origin 'https://my-app.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by francoisromain** [comment]
I didn't mention that on the production server,
we use this nginx proxy: https://github.com/jwilder/nginx-proxy

**Comment by francoisromain** [comment]
Ok. I finally found the source of the problem: 

On the production server , we use this nginx proxy: https://github.com/jwilder/nginx-proxy, which has a 2Mb default upload limit. We changed by setting the `client_max_body_size`. 

Thanks for your help

**Comment by mike-marcacci** [comment]
Aaah, that makes sense. Glad you figured it out!
