### ISSUE TITLE
Problem with Node v.13

### ISSUE THREAD

**Issue by direct808** [jaydenseric/graphql-upload#171]
When I call the createReadStream method, a GraphQL error occurs: Maximum call stack size exceeded

The problem arises precisely on the  node version 13. 

On versions below 13 there is no error. But it outputs: (node: 6750) [DEP0135] DeprecationWarning: ReadStream.prototype.open () is deprecated

  Tell me what this may be related to?

**Comment by jaydenseric** [comment]
Duplicates existing PRs and https://github.com/jaydenseric/graphql-upload/issues/170.
