### ISSUE TITLE
How to use graphql-upload in apollo-server-express?

### ISSUE THREAD

**Issue by adelmojnr** [jaydenseric/graphql-upload#174]

**Comment by jaydenseric** [comment]
As mentioned in the [readme support section](https://github.com/jaydenseric/graphql-upload#support) this package is implemented by `apollo-server-express`, so no setup necessary. Just use it.

There are usage instructions, API docs and examples in the readme here and in the Apollo docs.

**Comment by adelmojnr** [comment]
Thanks, bro.
