### ISSUE TITLE
Should throw error when a JSON instead of a File is received from client

### ISSUE THREAD

**Issue by HosseinAgha** [jaydenseric/graphql-upload#175]
When I send a JSON (number, string, object, etc) instead of a File from client, I don't get any errors and the argument returns a JS Object instead of [Promise\<FileUpload\>](https://github.com/jaydenseric/graphql-upload#type-fileupload).  
Is this working correctly? Shouldn't this throw an error in the `parseValue` of scalar? We are expecting a stream after all.  
This forces us to validate the input every time we are using `Upload` scalar.  

I'm using Apollo Server (and `apollo-upload-client` which does not matter in this scenario)

**Comment by mike-marcacci** [comment]
Thanks for the report @HosseinAgha. I can confirm what you're describing: when a variable of type `Upload` is provided by a variable but is _not_ supplied in the request (that is, not present in the map), the contents of the variable are never replaced. This should indeed cause an error.
