### ISSUE TITLE
Missing multipart field ‘operations’ when I use firebase functions

### ISSUE THREAD

**Issue by jeemyeong** [jaydenseric/graphql-upload#178]
I have some troubles to use graphql-upload when I use firebase functions.

https://github.com/prisma-labs/graphql-yoga/blob/master/examples/file-upload/index.ts
You can experience same error with this code and firebase functions.

I got a message `BadRequestError: Missing multipart field ‘operations’` for unknown reasons, but I tried to figure out what can make this error, so finally I got a hint in this code.

https://github.com/jaydenseric/graphql-upload/blob/1146cf404db481c8da52abd65b3897be0a6c175d/processRequest.js#L388

How about changing this code to `parser.end(request.rawBody)` like (https://cloud.google.com/functions/docs/writing/http#multipart_data)?

I am hoping this will solve my problem.

**Comment by jeemyeong** [comment]
I found this was a duplication of #129

**Comment by koresar** [comment]
Hey @jeemyeong 
I've forked graphq-upload and looking for someone to test how it works in GCF.
More details are in this comment: https://github.com/jaydenseric/graphql-upload/issues/155#issuecomment-641102784
