### ISSUE TITLE
Uploads option maxFileSize not working correctly

### ISSUE THREAD

**Issue by phuo1032** [jaydenseric/graphql-upload#183]
Opened a similar issue on apollo-server 
https://github.com/apollographql/apollo-server/issues/3703

But after some closer look to the source code the underlying issue may be in graphql-upload.

To recap, I have an apollo-server-express service that tried to setup upload size limit but only work for small size (typically less than the read stream chunk size). Here is what my resolver looks like

```
const upload = async(parent, { file }, context) => {
	const { createReadStream } = await file;
	const stream = createReadStream();
	// rest of the stream handling code
}
```

I played with some print out with this file
https://github.com/jaydenseric/graphql-upload/blob/73ef939ef16a40358eb80e0a54c5c3ead725b2fe/lib/processRequest.js

And notice that with a maxSize < 65536, 
`stream.on('limit', () => ` would occur before createReadSteam is called and createReadStream call itself is aware of and throw the error.

Otherwise `await file` is resolved before the stream reaches the limit, and createReadStream() will read data from stream until it reaches the limit, however
this line
https://github.com/jaydenseric/graphql-upload/blob/73ef939ef16a40358eb80e0a54c5c3ead725b2fe/lib/processRequest.js#L281
seems to only destroy the capacitor but does not throw the error back to the resolver. As a result the resolver just hangs around as the stream is no longer reading any more data.

The version of graphql-upload I am using is 8.1.0 if it makes any difference

**Comment by Javadebi** [comment]
Hello i want to make a upload resolver for my graphql project but inside apollo site didnt say anything.
can someone help me??
im using mongodb for database apllo-server-express and Express.

**Comment by jaydenseric** [comment]
@Javadebi this issue is not the appropriate place to ask for general help.

> inside apollo site didnt say anything

Apollo does have documentation on file uploads: https://www.apollographql.com/docs/apollo-server/data/file-uploads

Also, you can see Apollo upload examples here: https://github.com/jaydenseric/apollo-upload-examples

**Comment by jaydenseric** [comment]
@phuo1032  what is the version of Node.js? Also, could you please try the latest `graphql-upload` version and see if it is resolved?

**Comment by phuo1032** [comment]
@jaydenseric Latest release (10.0.0) seems to work for this issue fine but incompatible with the latest version of apollo-server-express. It results into an uncaught exception.

**Comment by jaydenseric** [comment]
Thanks for the update; we can reopen this issue if a reproducible bug is found in the latest `graphql-upload` version.
