### ISSUE TITLE
How to upgrade to v10?

### ISSUE THREAD

**Issue by j0k3r** [jaydenseric/graphql-upload#184]
That snippet doesn't work anymore: https://github.com/jaydenseric/graphql-upload#class-graphqlupload

In the `resolve` method, everything is `undefined`:

```js
const { filename, mimetype, createReadStream } = await image

console.log(filename, mimetype, createReadStream)
// undefined undefined undefined
```

How are we supposed to upgrade from v9?

It looks like `image` is now a dedicated class with properties `resolve`, `reject`, `promise` & `file` but according to [the doc](https://github.com/jaydenseric/graphql-upload#class-upload), most of them _should only be utilized by processRequest._.

Using `.promise` seems to solve the issue:

```js
const { filename, mimetype, createReadStream } = await image.promise
```

But `.file` seems to be the resolved promise:

```js
const { filename, mimetype, createReadStream } = image.file
```

Am I right?
Which one is the way to go?

**Comment by jaydenseric** [comment]
I apologise for the confusion! Some of the documentation is now incorrect; the issues slipped through review.

It should be like this:

```js
const { filename, mimetype, createReadStream } = await image.promise
```

The `filename`, etc. will always need to be awaited from a promise.

It's a bit annoying to have to add `.promise`, but it was the most expedient way to get automatic `GraphQLUpload` scalar value validation to work. The scalar needs to be able to validate that its value came from `processRequest`, and that the promise won’t resolve something unexpected.

I looked at using a subclass of `Promise` to enable `instanceof` checks, but it's not a very common pattern and were worries it might interfere with the polyfils/replacements people sometimes use. It also seems dubious to add a special symbol property onto `Promise` instances.

Within `processRequest` were already using the `Upload` class to track the status of upload promises, and the scalar can easily check the value is an instance of that class.

If people have a better suggestion, I'm open to improvements for future versions.

**Comment by jaydenseric** [comment]
Wait, I actually did account for this! The documentation should be correct… the scalar returns the `.promise` automatically:

https://github.com/jaydenseric/graphql-upload/blob/v10.0.0/lib/GraphQLUpload.js#L65

**Comment by jaydenseric** [comment]
I just double tested `graphql-upload` v10.0.0 on a real project (about to deploy it soon), and everything is fine. For a typical project, you don't need to change anything in your resolvers upgrading from v9 to v10:

```js
const { filename, mimetype, createReadStream } = await image
```

If you were doing your own validation in resolvers that the upload value is a promise, in case the client sent a random value such as a string or boolean, you can now remove that logic.

**Comment by jaydenseric** [comment]
Regarding your original issue, it looks like maybe the `GraphQLUpload` scalar is not coming from `graphql-upload` v10? Or the other way around, perhaps the old middlware/`processRequest` is running with the new scalar - could this be because you are Apollo Server?

**Comment by j0k3r** [comment]
You're right we used a custom type for the upload and not the one shipped with your lib.
Replacing it with `GraphQLUpload` fixed the issue.

Thanks for all the explanations and sorry for bothering you about that
