### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added

### ISSUE THREAD

**Issue by EhsanSarshar** [jaydenseric/graphql-upload#186]
I am trying to upload 12 image files to server but it log the following warning

`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added`

here is how I handle file upload in server side

```
const { createReadStream, filename, mimetype, encoding } = await receivedFile;

    const stream = createReadStream()

    const ext = mim.extension(mimetype)

    url = url +'.'+ext
    
    const path = Path.resolve(__dirname, '../../../public/images', url)

    const writer = fs.createWriteStream(path)

    stream.pipe(writer)

    await new Promise((resolve, reject) => {
        writer.on('finish', resolve)
        writer.on('error', reject)
    })

    writer.end()

    return url
```

> I am using graphql-upload@^10.0.0

**Comment by mike-marcacci** [comment]
Hi @EhsanSarshar, can you run `npm ls fs-capacitor` or `yarn why fs-capacitor`?

**Comment by mike-marcacci** [comment]
Re-reading this now, it's actually quite clear that this isn't a problem: by default node will "try to help" by providing this message whenever an event emitter has more than 10 listeners for an event.

You can change this by calling `.setMaxListeners(n)` on `process`, where `n` is the new warning threshold or zero to disable the warning entirely.

See [node's docs](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n) on the subject.
