### ISSUE TITLE
BadRequestError: Missing multipart field ‘operations’

### ISSUE THREAD

**Issue by dimaninc** [jaydenseric/graphql-upload#187]
I have read all the issues mentioned by github as similar to my, but there is no solution.

Here is my server backend base

```
const app = express();
app.use(cors());
app.use(
    '/graphql',
    graphqlUploadExpress({ maxFileSize: 50000000, maxFiles: 10 })
);
app.use('/graphql', bodyParser.json());
app.use(compression());
app.use(cookieParser());
app.use(fileUpload());
app.disable('x-powered-by');
```

versions of modules:

```
"apollo-server": "^2.10.0",
"graphql-upload": "^10.0.0",
```

So, I have installed `graphql-upload` and try to upload a file using browser and Altair (graphql playground analog supporting file uploads)

All my attempts to upload a file finish the same, I get the following error message:

> BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
> at Busboy.parser.once (ProjectName/node_modules/apollo-server-core/node_modules/graphql-upload/lib/processRequest.js:290:35)

Here is the `request.body` (it is the same both from browser and from Altair)

```
{ query:
   'mutation FileUpload($image: Upload!) {\n  fileUpload(\n    file: $image\n  ) {\n    tmpFilename\n  }\n}',
  variables:
   { file:
      Upload {
        resolve: [Function],
        reject: [Function],
        promise: [Promise],
        file: [Object] } },
  operationName: 'FileUpload' }
```

But as I see at link above (from error message), the backend app expects `operations` and `map` keys in request body.

Why does it expect these params if neither `apollo-react` nor `Altair` app doesn't send them?

**Comment by jaydenseric** [comment]
> But as I see at link above (from error message), the backend app expects `operations` and `map` keys in request body.

For file uploads the GraphQL API expects the request to be a multipart request, not a JSON POST requests, so those fields mentioned in the error are meant to be multipart request fields. If you are sure the client is sending a correct multipart request, you need to look at problems with how the server is configured.

I'm not sure what the `fileUpload` is, and I can't see Apollo Server in the middleware. Regarding `bodyParser.json()`, be aware that some body parser middleware interferes with with parsing multipart requests.

If you are trying to manually setup file uploads, remember to disable the file uploads feature completely in Apollo Server - I'll leave that to you to figure out how to do; I've explained how previously in other issue comments.

**Comment by dimaninc** [comment]
First, I thought that I make non-proper request from the frontend, but when I tried to emulate file upload in Altair and it made the same – I started to find the reason on the backend

I tried to comment out all other middlewares leaving only this:

```
const app = express();
app.use(cors());
app.use(
    '/graphql',
    graphqlUploadExpress({ maxFileSize: 50000000, maxFiles: 10 })
);
```

But the result is the same. And the request body is the same. And here is Altair window for the request:

![image](https://user-images.githubusercontent.com/4658059/74406028-a1a3e380-4e3f-11ea-945a-bc45ca015e71.png)

**Comment by dimaninc** [comment]
I've read some more articles on the internet and now I realize that both my frontend application and Altait send bad requests to backend, thank you for the direction of my search, I will post here a solution when it will be found

**Comment by dimaninc** [comment]
Unfortunately no result on frontend, this is my frontend code, I removed all other links, left only this

```
import { createUploadLink } from 'apollo-upload-client';
import { config } from '../config';

const cache = new InMemoryCache();

const uploadLink = createUploadLink({
    uri: config.graphql.uri(),
    headers: {
        'keep-alive': 'true',
    },
});

const client = new ApolloClient({
    link: uploadLink,
    cache,
});
```

And I still get non-multipart request to the backend while making this:

```
const FILE_UPLOAD_QUERY = gql`
    mutation FileUpload($file: Upload!) {
        fileUpload(file: $file) {
            filename
            tmpFilename
        }
    }
`;

const withFileUpload = graphql(FILE_UPLOAD_QUERY, {
    name: 'fileUpload',
});

```

```
       onChange: event => {
            if (event.currentTarget.validity.valid) {
                setUploading(true);
                const file = event.target.files[0];
                file &&
                    fileUpload({
                        variables: { file },
                    }).then(
                        props => {
                            setUploading(false);
                            console.log('uploadedFile', props);
                        },
                        error => {
                            setUploading(false);
                            console.log('fileUpload error', error);
                        }
                    );
            }
        }
```

**Comment by dimaninc** [comment]
I've also tried to change mutation approach from `graphql(...)` to `Mutation` component – all left the same. Where am I doing wrong?

**Comment by jaydenseric** [comment]
GitHub issues is not really the right place to ask for general help, with the exception of [people who sponsor my effort](https://github.com/sponsors/jaydenseric).

> I've also tried to change mutation approach

There is no reason to do any of that if you have already verified that the client is sending a correct [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec).

When file uploads are not working as expected, start verifying the client is setup perfectly and working, then move on to the server and do the same. I'm sure if everything was configured properly you won't have any troubles. Try to understand at a basic level how the different parts work; it might help in your troubleshooting.

I'm making the base assumption that you're deliberately not using the built in file upload support in Apollo Server Express (perhaps to use a newer `graphql-upload` version than Apollo ships with), which in most cases works out of the box without special config.

**Comment by Aslemammad** [comment]
For folks that encountered this issue, if you have middlewares like `express-fileupload` or `fileParser`, remove them; they won't let `graphql-upload` consume the data. That's how I solved it.

**Comment by Enmanuellperez98** [comment]
I solve it, by adding `uploads: false`:
    `const server = new ApolloServer({
        uploads:false,
        schema,
        playground: true
    });`

**Comment by natterstefan** [comment]
> I solve it, by adding `uploads: false`:
> `const server = new ApolloServer({ uploads:false, schema, playground: true });`

Thank you @Enmanuellperez98, that resolved the problem for me as well.

**Comment by giautm** [comment]
Resolve the problem by disable the feature, r u kidding? 🤨🤨

**Comment by natterstefan** [comment]
> Resolve the problem by disable the feature, r u kidding? 🤨🤨

Hi, I was skeptical as well, but actually, it did not disable the upload for me for my use case.

The mutation got the file still, and I was able to handle it, etc.

I don’t know what’s going on behind the curtains, but for our use case (test it for your case by yourself), it was sufficient.

**Comment by Enmanuellperez98** [comment]
It seems that in previous versions of Apollo Server, they had a built-in integration with `graphql-upload`. But in version 3 no, so you have to indicate with `uploads: false`, that you are integrating it yourself.

Take a look at this implementation of the repo author:
https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/server.mjs

````
new ApolloServer ({
   // Disable the built in file upload implementation that uses an outdated
   // `graphql-upload` version, see:
   // https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289
   uploads: false,
   schema,
}). applyMiddleware ({app}); 
````

**Comment by natterstefan** [comment]
Thank you very much for the clarification and links. Very helpful.

I hope you think again about downvoting the helpful answer above @giautm.

**Comment by nonils** [comment]
> > I solve it, by adding `uploads: false`:
> > `const server = new ApolloServer({ uploads:false, schema, playground: true });`
> 
> Thank you @Enmanuellperez98, that resolved the problem for me as well.

Thank you @Enmanuellperez98, it solved the problem for me too.

**Comment by 293nav** [comment]
> It seems that in previous versions of Apollo Server, they had a built-in integration with an old version of `graphql-upload`. So you have to indicate with `uploads: false`, that you are integrating it yourself.
> 
> Take a look at this implementation of the repo author: https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/server.mjs
> 
> ```js
> new ApolloServer ({
>    // Disable the built in file upload implementation that uses an outdated
>    // `graphql-upload` version, see:
>    // https://github.com/apollographql/apollo-server/issues/3508#issuecomment-662371289
>    uploads: false,
>    schema,
> }). applyMiddleware ({app}); 
> ```

Thank you, this solved my issue as well. Setting `uploads: false` in Apollo Server and then adding graphql-upload as middleware helped with the issue.

In my case the client was sending a request with `multipart/form-data` in the headers but the server was rejecting it as a bad request. Disabling the uploads in Apollo Server fixed the problem. 

**Note:** This solution is only for those using Apollo Server v2. In v3 I didn't face this issue and everything worked properly without setting `uploads: false`
