### ISSUE TITLE
fastify-gql support

### ISSUE THREAD

**Issue by artecoop** [jaydenseric/graphql-upload#189]
Has anyone tried to support fastify-gql via fastify-multipart (or similar)?
I'd love to help.

**Comment by bmullan91** [comment]
@jaydenseric I've created a fastify plugin that utilises `processRequest` - https://www.npmjs.com/package/fastify-gql-upload, seems to do the trick 👍

**Comment by mike-marcacci** [comment]
@artecoop it looks like @bmullan91 has your answer there! I'll close this here and let the discussion continue in [the relevant repo](https://github.com/bmullan91/fastify-gql-upload).
