### ISSUE TITLE
BadRequestError: Missing multipart field ‘operations’

### ISSUE THREAD

**Issue by ysz** [jaydenseric/graphql-upload#191]
Upload does not work 

Please see repro https://github.com/ysz/apollo-server-upload

**Comment by jaydenseric** [comment]
Well done of the very detailed repro 👏

Almost certainly this is your problem: https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-583572804

**Comment by Enmanuellperez98** [comment]
I solve it, by adding `uploads: false`:
    `const server = new ApolloServer({
        uploads:false,
        schema,
        playground: true
    });`
