### ISSUE TITLE
BadRequestError: form-data: Request disconnected during file upload stream parsing.

### ISSUE THREAD

**Issue by MustKillBill** [jaydenseric/graphql-upload#195]
Hey guys, thanks for the awesome library!

Currently using `apollo-server: 2.11.0` which includes `graphql-upload`.

I get the following error when I'm trying to stream image file from client to another http mecro-service:

```
BadRequestError: form-data: Request disconnected during file upload stream parsing.
    at IncomingMessage.abort (/Users/hansel/Documents/LIT/Development/creators-app/server/node_modules/graphql-upload/lib/processRequest.js:89:33)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:311:20)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at resOnFinish (_http_server.js:685:7)
    at ServerResponse.emit (events.js:323:22)
    at ServerResponse.EventEmitter.emit (domain.js:482:12)
    at onFinish (_http_outgoing.js:730:10)
    at onCorkedFinish (_stream_writable.js:721:5)
    at afterWrite (_stream_writable.js:528:5)
    at afterWriteTick (_stream_writable.js:515:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  message: 'form-data: Request disconnected during file upload stream parsing.',
  expose: true,
  statusCode: 499,
  status: 499
}
```

Request: 
```
export async function sendFile(file) {
  const { filename, createReadStream } = await file
  const stream = createReadStream()

  const options = {
    method: "POST",
    url: "http://localhost:5000/api/upload",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    formData: {
      file: {
        value: stream,
        options: {
          filename,
          contentType: null,
        },
      },
    },
  }

  request(options, err => console.log(err))
}

```

Resolver:
```
Mutation: {
  uploadFile: async (_, { file }) => (
    sendFile(file)
  )
}
```

Doing anything else (e.g. saving it, sending it to S3 bucket, etc.) The only problem is when sending it through a http request.

Also, performing the same request using `fs.createReadStream(filePath)` works too.

Any suggestions?

**Comment by jaydenseric** [comment]
See this tip:

> Promisify and await file upload streams in resolvers or the server will send a response to the client before uploads are complete, causing a disconnect.

https://github.com/jaydenseric/graphql-upload#tips

**Comment by Bdthomson** [comment]
@hanselabreu were you able to succeed with this? I am attempting the same thing (passing a file through graphql server to then pass via http to another microservice. I am running into the same issue, the data passed via FormData multipart is incomplete and malformed. 

Reading from a filepath works for me (as it does for you), and first converting the stream to bytes then sending along to a microservice works, but this is obviously not performant as the data would have to be read into memory.

**Comment by yaacovCR** [comment]
Things might work better with node-fetch v3 now in beta rather than v2 as there were some gotchas with FormData and streams with v2.

What toolset exactly are you using?

Relevant:
https://github.com/node-fetch/node-fetch/commit/a38b533ad68b333b46686034804c4b643de3b8d0
