### ISSUE TITLE
[Question] Best way to skip ASP.Net Core /Identity/Account/* 

### ISSUE THREAD

**Issue by lydonchandra** [jaydenseric/graphql-upload#198]
GraphQL-Upload tries to process login action in ASP.NET Core.
![image](https://user-images.githubusercontent.com/158145/80921334-5519d580-8da8-11ea-9c52-47c06c972e2d.png)

What is the best way of handling this? For now we can hardcode it to skip /Identity/Account/* urls

**Comment by jaydenseric** [comment]
I'm not familiar with ASP.NET or what is going on in that screenshot, but the `graphql-upload` Express and Koa middleware is only intended for use on the GraphQL endpoint, where it makes the assumption that any multipart request is a GraphQL multipart request.

**Comment by jaydenseric** [comment]
Closing because this issue is really a usage question, and I've already answered it as best I can. You might have better luck asking the question in forum specific to your chosen frameworks.
