### ISSUE TITLE
Graphql v15 support

### ISSUE THREAD

**Issue by rigelglen** [jaydenseric/graphql-upload#200]
Hi, graphql-upload currently does not include graphql 15.0 as a supported peer depenency. Even though graphql 15 came with some breaking changes, I don't think anything needs to be changed to support it.

**Comment by jaydenseric** [comment]
Yes, I plan to update the `graphql` peer dependency for all the packages I maintain sometime soon, e.g. https://github.com/jaydenseric/graphql-api-koa/issues/9 .
