### ISSUE TITLE
BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec)

### ISSUE THREAD

**Issue by moussouba** [jaydenseric/graphql-upload#207]
![Capture d’écran de 2020-05-24 17-21-15](https://user-images.githubusercontent.com/54843919/82760542-a20b2d80-9de3-11ea-9c1f-65a96334118a.png)

the variable **operations** on the lib/processRequest.js file at line 315 is always undefined

**Comment by jaydenseric** [comment]
Perhaps the error message is correct, the multipart form field `operations` is missing from the request.

**Comment by moussouba** [comment]
the multipart form field operations is there; on the request body

**Comment by jaydenseric** [comment]
In the Chrome network inspector, in the outgoing request you should be able to see the multipart form, and it should look something like this:

https://github.com/jaydenseric/graphql-multipart-request-spec#request-payload

**Comment by gpDA** [comment]
does anyone experience the same issue?

The following is my request payload

I use form Data to send the file
<img width="633" alt="image" src="https://user-images.githubusercontent.com/29666846/165620679-09748f71-489a-4641-a564-c140d996c6cd.png">
