### ISSUE TITLE
Upload scalar return empty object as resolver argument

### ISSUE THREAD

**Issue by mittalyashu** [jaydenseric/graphql-upload#211]
**Schema**

```
scalar Upload

type Mutation {
  uploadImage(image: Upload): Image
}
```

**Resolver**

This is the resolver to import `Upload` scalar

```js
const { GraphQLUpload } = require('graphql-upload');

module.exports = {
  Upload: GraphQLUpload
}
```

Resolver to handle image upload

```js
const uploadImage = input => {
  const data = { ...input }
  console.log(data)

  // upload to image server
}

module.exports = {
  uploadImage
}
```

The `Data` variable return `{ image: {} }`

**Comment by jaydenseric** [comment]
First, make sure the client is sending a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec) to the server. Use the Chrome dev tools network inspector to verify this.

Secondly, make sure the [`graphqlUploadKoa`](https://github.com/jaydenseric/graphql-upload#function-graphqluploadkoa) or [`graphqlUploadExpress`](https://github.com/jaydenseric/graphql-upload#function-graphqluploadexpress) middleware is setup correctly.

Make sure no other middleware is parsing the multipart request, particularly before the `graphql-upload` middleware.

**Comment by mittalyashu** [comment]
I believe the issue is not from GraphQL server instead from the resolver itself.

Though, I did check all the things you have mentioned add made the required changes for `graphqlUploadExpress`.

And, the problem seems still persistent.

**Comment by jaydenseric** [comment]
If in the server project you run `npm ls graphql-upload`, is there only one version installed? If not, you need to make sure that only once version is being used so that the middleware and scalar can work together properly.

**Comment by mittalyashu** [comment]
`└── graphql-upload@11.0.0`

Yup, using latest version.

Does it request to install this package in frontend (react.js project) where we use the mutation.

```js
const mutationUploadImage = gql`
  mutation UploadImage(
    $image: Upload!
  ) {
    uploadImage(image: $image) {
      publicLink
    }
  }
`
```

**Comment by jaydenseric** [comment]
You should have already verified that the front end is sending a valid GraphQL multipart request, so it is irrelevant at this point.

**Comment by mittalyashu** [comment]
I have double checked the mutation query in the frontend and there seems nothing wrong with that.

But, after inspecting the network tab, it seems it is not able to add the File blob as a variable.

<img width="824" alt="Screenshot 2020-06-27 at 3 29 19 PM" src="https://user-images.githubusercontent.com/29014463/85919677-3527ff00-b88b-11ea-957f-491008debba9.png">

**Comment by jaydenseric** [comment]
That doesn't look like a multipart request; your problem is on the client. Setup your client to send the right requests; here are a list of client implementations to choose from:

https://github.com/jaydenseric/graphql-multipart-request-spec#client
