### ISSUE TITLE
@types/graphql-upload is outdated

### ISSUE THREAD

**Issue by mschipperheyn** [jaydenseric/graphql-upload#214]
I'm not sure if you maintain this, bit It still has a dependency on graphql 14

**Comment by jaydenseric** [comment]
I don't maintain the [`@types/graphql-upload`](https://www.npmjs.com/package/@types/graphql-upload) package, please file an issue or PR at Definitely Typed :)

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/graphql-upload

**Comment by Daavidaviid** [comment]
I solved this issue following this guide 
https://stackoverflow.com/questions/40322788/how-to-overwrite-incorrect-typescript-type-definition-installed-via-types-packa

**Comment by jasonlimantoro** [comment]
Can you share your definition file? @Daavidaviid
