### ISSUE TITLE
Question about 'Upload value invalid' error.

### ISSUE THREAD

**Issue by flashcrow2000** [jaydenseric/graphql-upload#219]
Hi! I'm sorry if this is not the best way for adding this, please direct me to a better place if that's the case. I followed your implementation for adding Upload capabilities to an existing application. The code uses the `GraphQLUpload` and `FileUpload` classes, and the mutation looks something like this:

```js
@typeGraphql.Mutation(() => Boolean)
    async addProfilePicture(
        @typeGraphql.Arg("picture", () => GraphQLUpload)
        {
        createReadStream,
        filename
        }: FileUpload): Promise<boolean> {
      return new Promise(async (resolve, reject) =>
        createReadStream()
          .pipe(createWriteStream(__dirname + `/../../../images/${filename}`))
          .on("finish", () => resolve(true))
          .on("error", () => reject(false))
      );
    }
```

In Postman I have the following body:

```
operations:{"query":"mutation addProfilePicture($picture: Upload!) {addProfilePicture(picture: $picture)}", "variables": {"picture": null}}
map:{"0":["variables.picture"]}
```

and a local file added in the '0' field.

when running a query with Postman, I get the error:

```
Variable \"$picture\" got invalid value {}; Expected type Upload. Upload value invalid
```

I've been at this for 3 days already. could use a bit of help..

**Comment by jaydenseric** [comment]
It sounds like you are having a similar issue to this:

https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-583510118

Here is an explanation:

https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-583572804

**Comment by thachp** [comment]
@flashcrow2000  you had any luck resolving this issue?

**Comment by flashcrow2000** [comment]
no, I reverted to using a REST endpoint for upload .. it works all fine and
dandy in a standalone project, but not in the one I'm doing. It probably is
related to type graphql, i don't know.

**Comment by thachp** [comment]
@flashcrow2000  It took me a while to solve this problem.  Give this a try... it worked for me. 
I'm using Node 15

1. Add to package.json
```
    "resolutions": {
        "graphql-upload": "^11.0.0"
    },
```

2. Check to make sure that there is only one graphql-upload folder under your node_modules.   I used yarn why, and manually checked dir node_modules/apollo-server-core/node_modules.  There should only be three visible dir under it .. (apollo-graphql, apollo-server-types and graphql-tools)

```
yarn why v1.22.4
[1/4] Why do we have the module "graphql-upload"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "graphql-upload@11.0.0"
info Reasons this module exists
   - "apollo-server-core" depends on it
   - Hoisted from "apollo-server-core#graphql-upload"
   - Hoisted from "@nestjs#graphql#apollo-server-core#graphql-upload"
info Disk size without dependencies: "1.19MB"
info Disk size with unique dependencies: "2.27MB"
info Disk size with transitive dependencies: "3.33MB"
info Number of shared dependencies: 18
Done in 0.80s.

```

3. If you are using ApolloClient, make sure that you include the createUploadLink...
```
import { createUploadLink } from "apollo-upload-client";
...
export const gclient = new ApolloClient({
    cache: new InMemoryCache(),
    link: createUploadLink(),    
    uri: "/graphql"
});

```

4. When filing your input variables, make sure that the file input value is type _File_ or _Blob_. https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-583572804

**Comment by iam4x** [comment]
I've posted an easy workarround https://github.com/jaydenseric/graphql-upload/issues/185#issuecomment-758822484

**Comment by stomvi** [comment]
If you're using `next.js` and the `resolutions` doesn't work for you, you might want to try this:
(#216)[https://github.com/jaydenseric/graphql-upload/issues/216#issuecomment-836591589]

**Comment by masoudit** [comment]
Hi, it depends on ApolloClient that you used.
If used import { ApolloClient } from 'apollo-client' must be used "createUploadLink" instead of "createHttpLink "means,
```
import { createUploadLink } from 'apollo-upload-client'
const httpLink3 = createUploadLink({
  uri: httpEndpoint,
})
```
