### ISSUE TITLE
Issue uploading a file with non-English filename

### ISSUE THREAD

**Issue by jchariot** [jaydenseric/graphql-upload#222]
```
var my_graphQL_func = {
  type: responseType,
  args: {
	file_upload: { type : GraphQLUpload, required: true }
  },
  resolve: async (_, args) => {
	  ...
    console.log( args.file_upload )
	...
  }
```

I am using GraphQLUpload. Everything works ok, but whenever I upload a file that contains non-English characters in the file's name, the app seems to . For example, I got a file named "平仮名.pdf". When I uploaded it in, this is what I got from console.log above:

```
Promise {
  { filename: 's�\r.pdf',
    mimetype: 'application/pdf',
    encoding: '7bit',
    createReadStream: [Function: createReadStream] } }
```

So "平仮名.pdf" became "s�\r.pdf" . This occurs with other languages as well. How do I fix this issue?

**Comment by jaydenseric** [comment]
If you use the chrome network inspector to look at the outgoing GraphQL request, in the request body in the multipart string do the file field names look correct?

**Comment by jchariot** [comment]
> If you use the Chrome network inspector to look at the outgoing GraphQL request, in the request body in the multipart string do the file field names look correct?

My code is on node.js, and I am using Postman to do a post request to node.js. All of this is on localhost. 

For additional information, GraphQL returned this 500 Internal Server Error and this:

`{
    "errors": [
        {
            "message": "Cannot read property 'statuscode' of null"
        }
    ]
}`

> Chrome network inspector to look at the outgoing GraphQL request

Sorry, I am not sure how to do this. Would you mind give me some pointers?

**Comment by jchariot** [comment]
In node.js app, I logged out the request.body.variables.file1 out:

app.use(
  entry_url,
  graphqlUploadExpress({ maxFileSize: 4000000, maxFiles: 10 }),
  graphqlHTTP((request) => {
	  console.log( request.body.variables.file1 )
    return {
      schema: inputSchema,
      context: { startTime: Date.now(), bodyQuery: request.body.query}, 
      originalContext: request },
      graphiql: true,
      extensions,
    };
  }),
);

and I got the following:

```
Upload {
  resolve: [Function],
  reject: [Function],
  promise:
   Promise {
     { filename: 's�\r.pdf',
       mimetype: 'application/pdf',
       encoding: '7bit',
       createReadStream: [Function: createReadStream] } },
  file:
   { filename: 's�\r.pdf',
     mimetype: 'application/pdf',
     encoding: '7bit',
     createReadStream: [Function: createReadStream] } }
```

**Comment by jaydenseric** [comment]
Personally I don't use Postman, but it seems you can easily open a network inspector this way:

<img width="739" alt="Screen Shot 2020-10-19 at 9 19 02 pm" src="https://user-images.githubusercontent.com/1754873/96434608-3671a300-1251-11eb-8963-3fb6114f3b10.png">

It would be good to figure out if the filenames are being sent correctly from the client. If they are not, then we know the problem is on the client.

**Comment by jchariot** [comment]
> Personally I don't use Postman, but it seems you can easily open a network inspector this way:
> 
> <img alt="Screen Shot 2020-10-19 at 9 19 02 pm" width="739" src="https://user-images.githubusercontent.com/1754873/96434608-3671a300-1251-11eb-8963-3fb6114f3b10.png">
> 
> It would be good to figure out if the filenames are being sent correctly from the client. If they are not, then we know the problem is on the client.

Upon further inspection. We created another tiny app to test this, and the tiny app could send files with non-English name to the node.js app without any issue. Therefore, Postman (v7.34.0) is at fault here.
