### ISSUE TITLE
`map` field in context of backward compatibility

### ISSUE THREAD

**Issue by o-rumiantsev** [jaydenseric/graphql-upload#227]
Hi, I am upgrading old GraphQL dependencies on my project. For file uploads apollo-upload-server@2.0.3 is used (I understand that now there is version 11 :)). We have a lot of users using mobile client, so we have no ability to update all our clients.
How should I deal with map property which is required now, but is not sent from most of the clients?

I am using:
Fastify - as a web framework
Mercurius - as fastify gql plugin
MercuriusUpload - as gql upload plugin

**Comment by jaydenseric** [comment]
`apollo-upload-server` was deprecated 2 years ago; I can only support the current `graphql-upload` version, sorry!

Please, please, _please_ update to the current `graphql-upload` version so you can benefit from all the bug and security fixes. `apollo-upload-server@2.0.3` was released 3 and a half years ago!

Regarding migrating your existing API; that is something you're in the best position to figure out as I don't know all the details of your apps, users, and business requirements. If you don't want to update your API and apps all at the same time, or create a second API endpoint, you could try to engineer some sort of solution where both systems work on the same endpoint - perhaps by updating your apps to send a custom HTTP header with their modern GraphQL multipart requests, so you know in the API to process it using the newer middleware. I'm exactly sure how it could work but you might need to create some middleware that runs after the legacy middleware to ensure the `Upload` scalars get values of the right type.

Plenty of apps (like Slack, Skype, Zoom?) occasionally say an update is required to continue using the app/service. Maybe that is an option for you?
