### ISSUE TITLE
Upload is missing as an export in Typescript definitions

### ISSUE THREAD

**Issue by ArrayKnight** [jaydenseric/graphql-upload#231]
![image](https://user-images.githubusercontent.com/5431637/103448659-768dd280-4c51-11eb-943e-4f67d58c2469.png)

I think I can just use `Promise<FileUpload>` for now, will be trying to set this up soon

**Comment by jaydenseric** [comment]
The `graphql-upload` TypeScript definitions are managed in another repo, at Definitely Typed:

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/0b5bfba2994c91a099cd5bcfd984f6c4c39228e5/types/graphql-upload

**Comment by MartijnHols** [comment]
I ran into this as well while setting up the project. For me I only thought I needed `Upload` because of a misconfiguration. If the middleware is correctly applied, the output should be the `FileUpload` type, not `Upload`. `Upload` is an internal type.

The issue for me was:

```
  expressServer.use(
    // graphqlPath, // <-- if you enable this line, the middleware will not be applied correctly
    graphqlUploadExpress(),
  )

  apolloServer.applyMiddleware({
    app: expressServer,
    path: graphqlPath,
  })
```
