### ISSUE TITLE
how to handle maxFileSize errors with graphqlUploadExpress

### ISSUE THREAD

**Issue by rafinskipg** [jaydenseric/graphql-upload#235]
Hello, sorry if this is a duplicate, i didn't found it.

How one can handle the maxFileSize error with express?

I am seeing this error
```
UnhandledPromiseRejectionWarning: PayloadTooLargeError: File truncated as it exceeds the 100000 byte size limit.
```

But I don't see how to attach any callback to the graphqlUploadExpress

Thanks

**Comment by jaydenseric** [comment]
Are you handling file upload stream errors?

https://github.com/jaydenseric/apollo-upload-examples/blob/be1444a0aa8768c6fe2e2c96119eb2b6344fcc50/api/server.js#L43-L54

**Comment by rafinskipg** [comment]
How do you handle the file upload stream errors?

I just followed the documentation: 

```
app.use(graphqlUploadExpress({ maxFileSize: 1000000, maxFiles: 10 }));
```

**Comment by jaydenseric** [comment]
@rafinskipg I linked an example in [the previous comment](https://github.com/jaydenseric/graphql-upload/issues/235#issuecomment-784921203).

**Comment by rafinskipg** [comment]
I'm sorry but it does not seem to work with my current set-up. 

It seems that the error is launched when `createReadStream` because the file is bigger than the size. Anyway, wrapping `createReadStream` with a try/catch seems to work for me! Thanks Mr jaydenseric. May the force be with you

**Comment by akristmann** [comment]
> I'm sorry but it does not seem to work with my current set-up.
> 
> It seems that the error is launched when `createReadStream` because the file is bigger than the size. Anyway, wrapping `createReadStream` with a try/catch seems to work for me! Thanks Mr jaydenseric. May the force be with you

I had the same problem and this was the only solution that worked for me. Thank you Rafin!
