### ISSUE TITLE
An example without using express (apollo server only)

### ISSUE THREAD

**Issue by omar-dulaimi** [jaydenseric/graphql-upload#249]
Hello,

Is it possible to get a working example of integrating this with a pure apollo server?

I don't use apollo server express, but couldn't find anything in that regard.

Thanks in adavnce

**Comment by jaydenseric** [comment]
What do you mean by "pure apollo server"?

**Comment by omar-dulaimi** [comment]
Like without using a middleware approach. Just plain apollo server; no express, no koa, etc.

**Comment by jaydenseric** [comment]
You should be able to get that going, but I can't recall off the top of my head the exact code. I suggest asking Apollo for assistance with their products.

Feel free to share the answer here once you figure it out in case others are wondering the same thing.
