### ISSUE TITLE
throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey)

### ISSUE THREAD

**Issue by nikunj321** [jaydenseric/graphql-upload#254]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './public/GraphQLUpload.js' is not defined by "exports" in A:\\ksproblem\\my-app\\node_modules\\graphql-upload\\package.json

**Comment by jaydenseric** [comment]
Update your dependencies, if you are using the current `graphql-upload` version that error wouldn't happen.

**Comment by jaydenseric** [comment]
Also, make sure your Node.js or bundler version is recent enough to support [package `exports` field subpath patterns](https://nodejs.org/api/packages.html#packages_subpath_patterns):

https://github.com/jaydenseric/graphql-upload/blob/bdb5f808e0d514c28c0f59c1abd71680aba29bae/package.json#L40

**Comment by nikunj321** [comment]
thank you.
