### ISSUE TITLE
No docs for how to use graphql-uploads with node 14  + apollo v2

### ISSUE THREAD

**Issue by zodman** [jaydenseric/graphql-upload#266]
```
import { GraphQLUpload } from 'graphql-upload';
const resolvers = {
...
Upload: GraphQLUpload 
}

 const server = new ApolloServer({
    resolvers,
    typeDefs,
    uploads:false
)
```
but is incomplete .....

**Comment by zodman** [comment]
I can only reference https://github.com/apollographql/apollo-server/issues/5230

**Comment by jaydenseric** [comment]
That is more of an Apollo Server question than a `graphql-upload` one. Here are the docs:

https://www.apollographql.com/docs/apollo-server/v2/data/file-uploads/#uploads-in-node-14-and-later
