### ISSUE TITLE
GraphQLUpload with processRequest on apollo-server-micro not working

### ISSUE THREAD

**Issue by jorgev259** [jaydenseric/graphql-upload#280]
When uploading a file im getting the following error.

![imagen](https://user-images.githubusercontent.com/19596334/143669581-fc0db7c4-2d74-44d6-af33-49e61471c5b8.png)

Server code:
```
const apolloServer = new ApolloServer({
  credentials: true,
  typeDefs: mergeTypeDefs(loadFilesSync(path.join(process.cwd(), 'graphql/schemas'))),
  resolvers: mergeResolvers([...Mutation, ...Query, ...types]),
  context: async ({ req, res }) => {
    const username = req.session.get('username')
    return { db, req, res, username, user: username && await db.models.user.findByPk(username) }
  }
})
const startServer = apolloServer.start()

export default withSession(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Credentials', 'true')
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')

  const contentType = req.headers['content-type']
  if (contentType && contentType.startsWith('multipart/form-data')) {
    req.filePayload = await processRequest(req, res)
  }

  await db.sync()
  await startServer

  return apolloServer.createHandler({ path: '/api/graphql' })(req, res)
})

export const config = {
  api: { bodyParser: false }
}
```

Resolvers object:
![imagen](https://user-images.githubusercontent.com/19596334/143669609-2aff36d5-e4fc-4892-8f3a-68ee12843f99.png)

**Comment by jaydenseric** [comment]
What might be happening is that there are multiple installations/versions of `graphql-upload`, and one is being used for the middleware and another is being used for the `Upload` scalar. This causes a conflict; there should be only one version of `graphql-upload` integrated.

If you're using an old version of Apollo Server that automatically integrates an outdated version of `graphql-upload`, you need to opt out. From memory, you can do that via an Apollo Server contractor option `uploads: false`.

Once you have disabled Apollo's integration, follow the setup instructions in the `graphql-upload` readme carefully.

**Comment by jorgev259** [comment]
uploads is already set to false, and apollo-server-micro in my current installation seems to be using 3+ apollo-server 
![imagen](https://user-images.githubusercontent.com/19596334/143669979-5f149214-e111-406e-afa2-cf85faa04690.png)

**Comment by jaydenseric** [comment]
Silly question, but is what you're using the variable `$cover` for in the GraphQL query correctly an `Upload` scalar? Maybe you're trying to use a file where some other kind of type is expected.

**Comment by jorgev259** [comment]
It is, `yarn why` showed the direct graphql-upload dependency as the only one. But it seems a similar problem as other issues was the culprit.

Solved by using the full path to import the Scalar: `import { GraphQLUpload } from 'node_modules/graphql-upload/public/index.js'`

**Comment by jaydenseric** [comment]
Sounds like something weird about how dependencies are installed and resolved in your project.

BTW, it's best to skip the index module and directly deep import the thing you need:

```js
import GraphQLUpload from 'graphql-upload/public/GraphQLUpload.js';
```

Or for your funny workaround:

```js
import GraphQLUpload from 'node_modules/graphql-upload/public/GraphQLUpload.js';
```
