### ISSUE TITLE
Support for `graphql` v16

### ISSUE THREAD

**Issue by saihaj** [jaydenseric/graphql-upload#281]
Hey, I see https://github.com/jaydenseric/graphql-upload/commit/0222da1a35e70b5439963a7181021690f4ea39a0 support for `v16` was added here but it was never published can you please cut a new release? Thanks!

**Comment by jaydenseric** [comment]
I've been working through the whole weekend to update various packages (e.g. https://github.com/jaydenseric/graphql-react/releases/tag/v16.0.0), and hope to be able to return to this one within the next day or so. There might be some other semver major changes to slip into the release. There is an important PR (https://github.com/jaydenseric/graphql-upload/pull/273) that I was hoping to have someone else review before publishing, but it's been a month so I think we'll just merge and YOLO it.

**Comment by jaydenseric** [comment]
This is no longer an issue in [v13.0.0](https://github.com/jaydenseric/graphql-upload/releases/tag/v13.0.0) 🚀
