### ISSUE TITLE
All promises are not resolved when i upload multiple files.

### ISSUE THREAD

**Issue by francelwebdev** [jaydenseric/graphql-upload#284]
Hello,
I have a problem when i upload multiple files, i don't know why all the promises are not resolved.
Please help me.
When I upload a single file the promise is resolved well and I can upload the file to an S3 service, but when I upload multiple files, say 3 or 4 files, only one or two file is resolved and everything else is pending.

Here is what I have in the terminal

![image](https://user-images.githubusercontent.com/18377068/144587905-5cdb6a9a-2210-4157-8bb1-f38014818351.png)

Here is the code

![image](https://user-images.githubusercontent.com/18377068/144588124-a43e3fe5-e10c-4285-857c-878279f2ddf8.png)

**Comment by jaydenseric** [comment]
The way the `graphql-upload` API is being used doesn't look right. I'm not sure what the `.value` is that you're awaiting, but an `Upload` scalar when awaited shouldn't resolve the `Upload` class like that. That class is an internal `graphql-upload` implementation detail you shouldn't be exposed to in resolvers. Maybe `graphql-upload` hasn't been installed properly, or there are multiple installations of different versions conflicting?

**Comment by francelwebdev** [comment]
Thank you for your quick reply.
Here is the content of the server file.
![image](https://user-images.githubusercontent.com/18377068/144601889-f65cea8e-852e-4fc8-8bab-e20f792a938f.png)
![image](https://user-images.githubusercontent.com/18377068/144601973-b9d9a608-9187-44d1-a085-72092b974daa.png)

And here is the top of the resolvers file.
![image](https://user-images.githubusercontent.com/18377068/144602101-92a6677d-d1d8-41c1-aee3-c4a2fad33fe0.png)

And here is the end of the resolvers file.
![image](https://user-images.githubusercontent.com/18377068/144602263-a883d7cb-6764-4e6b-9182-1a1c9a27890d.png)

**Comment by francelwebdev** [comment]
when i submit the form with the images attached, here is what i have in the browser console.
![image](https://user-images.githubusercontent.com/18377068/144603064-5c69af1b-e2d3-4baf-87b5-653907a1c48b.png)

**Comment by francelwebdev** [comment]
And in the terminal this is what I have.
![image](https://user-images.githubusercontent.com/18377068/144603351-2ff5f663-ee24-496b-8520-b4730a0f2d2e.png)

![image](https://user-images.githubusercontent.com/18377068/144603464-4b04befc-5ed0-48d9-a5a3-9483b9722ba3.png)

As you can see from the images, only one file was solved, the others were not solved while everything has to be solved so that I can send the files to s3.

**Comment by jaydenseric** [comment]
From memory `buildSchema` from GraphQL.js is not able to handle custom scalars, in this case `GraphQLUpload` from `graphql-upload`. I'm not sure this is the best link I can find on the topic, but here is a relevant StackOverflow question and answer: https://stackoverflow.com/questions/47824603/graphql-custom-scalar-definition-without-graphql-tools .

Most people who like to use a big GraphQL SDL string to design the schema and merge it with implementation code use third party libraries to do it. I really, _really_ recommend just using pure JavaScript and GraphQL.js to define your schema. It's much more efficient, requires no third party libraries, and allows you to modularise it very easily using basic JS modules. You can also dynamically code details of the types, e.g. use a template string to create a type description.

**Comment by francelwebdev** [comment]
Thank you again for your help.
I was using the graphql js package directly, then I'm going to remove the package and use graphql-tool. thanks again.

**Comment by jaydenseric** [comment]
Glad to have helped :)

**Comment by Tommy2212** [comment]
I have the same issue but I can not found the solution, can you help me?

**Comment by Tommy2212** [comment]
This is resolver 

![image](https://github.com/jaydenseric/graphql-upload/assets/62123376/ffa13389-dcfa-46ba-8fa7-5be6a86b10db)
