### ISSUE TITLE
FileList is supported but not an array/object with multiple files.

### ISSUE THREAD

**Issue by mateusmx** [jaydenseric/graphql-upload#291]
Hi. I'm facing with an issue where I'm able to get multiple files when making a simple `<input type="file" multiple>` but I'm facing issues when trying to integrate Dropzone UI which is giving me back an Array of files. 

I'm using type-graphql with apollo-server-exprees. Here is my resolver:

  ```
@Mutation(() => Boolean)
  @UseMiddleware(isAdmin)
  async fileUpload(
    @Arg('files', () => [GraphQLUpload])
    filesArray: Array<FileUpload>,
  ) {
    filesArray.map(async (item) => {
      const { createReadStream, filename } = await item;

      const fileRenamer = (filename: string): string => {
        const queHoraEs = Date.now();
        const regex = /[\s_-]/gi;
        const fileTemp = filename.replace(regex, '.');
        let arrTemp = [fileTemp.split('.')];
        return `${arrTemp[0]
          .slice(0, arrTemp[0].length - 1)
          .join('_')}${queHoraEs}.${arrTemp[0].pop()}`;
      };

      const stream = createReadStream();
      const assetUniqName = fileRenamer(filename);
      const pathName = path.join(__dirname, `../uploads/${assetUniqName}`);
      await stream.pipe(fs.createWriteStream(pathName));
      const urlForArray = `${process.env.SERVER_URL}/${assetUniqName}`;
      console.log(urlForArray);
    });
    return true;
  }
```

And here is a picture of what I send (In the top the 'failing' in the bottom the 'success'. In the top I manually made an object with the array of files I get from dropzone in the bottom is what I get from the regular input file)

![Captura de Pantalla 2022-01-16 a la(s) 15 52 38](https://user-images.githubusercontent.com/14305038/149680218-d7d696b9-610f-49da-bcba-caf27ae000c6.png)

I find out that FileList is a read-only and we can't create one from 0. So I'm stuck here. Also Attaching a picture of the answer I get from the BE.

 
![image](https://user-images.githubusercontent.com/14305038/149680278-14f02492-097f-4507-998b-64e3485515d5.png)

And this of course is only happening when trying to push from the Object I created or from the Array I got from Dropzone (tried both ways).
 
 
 Any help is very much appreciated.

**Comment by jaydenseric** [comment]
Always the first thing to do when'd debugging GraphQL file upload problems is to check if the client is sending valid [GraphQL multipart requests](https://github.com/jaydenseric/graphql-multipart-request-spec) to the server. This way, you can focus on which side is faulty, instead of wondering.

To do this, make the request with you browser's network inspector open. You should be able to inspect the `body` of the multipart request and make sure it follows the spec. Binary file data is hidden in the inspector for file fields, that's ok.

**Comment by mateusmx** [comment]
Thanks @jaydenseric  for such a quick response.


This is what I get from the one that fails:
![image](https://user-images.githubusercontent.com/14305038/149684204-3cd42958-1aa9-4a1f-bf85-fdc4995edde1.png)

This is what I get from the one that pass through
![image](https://user-images.githubusercontent.com/14305038/149684251-1c30d6d8-b182-4944-b954-6e091e0f6be6.png)

Pretty much the same, but what I can see is that for some reason they are getting 'mapped' differently 🤔  Any thoughts on that ?

**Comment by jaydenseric** [comment]
For the one that fail, you say in the GraphQL query that `files` is an array, but if you look at `files` within the GraphQL operation `variables` JSON, it's an object. That's you problem, it should be an array. This is a problem with how your client is preparing the `variables`, not a problem on the server or an issue with `graphql-upload`.

**Comment by mateusmx** [comment]
Hi @jaydenseric I did tried both methods (as an Array and as an Object) and keep having the same failure. Attaching pictures of what I get when I send an array:
![image](https://user-images.githubusercontent.com/14305038/149690248-9ec1e365-4447-4e9d-b1d8-6c220e3b6f3b.png)

![image](https://user-images.githubusercontent.com/14305038/149690306-070137b1-f87c-4a30-bf64-86b063f1205b.png)

![image](https://user-images.githubusercontent.com/14305038/149690328-1a44f0aa-603a-4ec5-a5ce-54bee6f2444a.png)

**Comment by jaydenseric** [comment]
@mateusmx  consider carefully this part of your query: `$files: [Upload!]!`. What you are doing in `variables` JSON is not that. You are doing an array that incorrectly contains objects that have the `Upload` scalar nested a layer deeper.

**Comment by mateusmx** [comment]
Hi @jaydenseric. I was able to make it work. Apparently when I was sending the array from the Dropzone integration, it was being 'rejected' with the errors shared before. So what was needed to do is to iterate that array from Dropzone and create a new one with only the file. I'll try to get sometime to write an article and share it so more persons can solve this. 

Thank you so much for your help.
