### ISSUE TITLE
Error: Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by brahimouindali** [jaydenseric/graphql-upload#299]
This is a simple demo for my case.
https://codesandbox.io/s/reverent-hill-b4cohz?file=/pages/index.js
it's very basic.
so when I try to upload a file I get the response POST body missing, invalid Content-Type, or JSON object has no keys
everything is working mutations and queries but the upload files not.
![graphql-upload](https://user-images.githubusercontent.com/62973203/157000818-24cd449e-c3fa-4e49-ac5f-bcd14bc11e16.png)
could you please help me out because I can't figure it out,
THANKS

**Comment by jaydenseric** [comment]
It appears you haven't setup the `graphql-upload` middleware, so the raw multipart request is hitting Apollo Server and it doesn't know how to process it. Please follow the `graphql-upload` installation instructions closely:

https://github.com/jaydenseric/graphql-upload#installation
