### ISSUE TITLE
PayloadTooLargeError: File truncated as it exceeds the byte size limit.

### ISSUE THREAD

**Issue by AlexJohnSadowski** [jaydenseric/graphql-upload#300]
I know the error is quite old, but I think it's still relevant. Or something's missing from the documentation, because I cannot find the way to catch that error in my application, hence it crashes the server. Try-catch doesn't work, Promises don't work. What's the solution to handle that? Read bunch of threads, but none of it helps. Ofc. if the file is smaller all works perfectly.

**index.js**

 ```
 async function startServer() {
    const server = new ApolloServer({
      typeDefs,
      resolvers,
      context: ({ req }): Dependencies => new Dependencies(container),
    });
    await server.start();

    const app = express();

    // This middleware should be added before calling `applyMiddleware`.
    app.use(graphqlUploadExpress({ maxFileSize: 1000000, maxFiles: 10 }));


    server.applyMiddleware({ app });

    await new Promise<void>((r) => app.listen({ port: process.env.PORT || 4000 }, r));

    console.log(`🚀 Server ready at http://localhost:${process.env.PORT || 4000}${server.graphqlPath}`);
  }
  await startServer();
})();
```

**Mutation:**
 ```
public async photoUpload(file: Photo) {
    try {
      const { createReadStream, filename, mimetype, encoding } = await file;
      const stream = createReadStream();

      if (mimetype === 'image/png' || mimetype === 'image/jpg' || mimetype === 'image/jpeg') {
        this.azureBlobStorageService.uploadFile('images', stream);
        return { filename, mimetype, encoding };
      } else return console.log('Wrong file type or the file is too big!');
    } catch (error) {
      console.log(error);
    }
  }
}
```

**Error:**

```
/node_modules/graphql-upload/public/processRequest.js:264

 fileError = createError(
                    ^
PayloadTooLargeError: File truncated as it exceeds the 1000000 byte size limit.
```

**Package.json**

```
  "apollo-server": "^3.4.0",
    "apollo-server-express": "^3.6.7",
    "fs-capacitor": "^7.0.1" (installing it doesn't change anything)
    "graphql": "^15.7.2",
    "graphql-upload": "^13.0.0",
```

**Comment by AidaRvi** [comment]
What happen to this question? I have the save issue here
@AlexJohnSadowski

**Comment by reda-xk7** [comment]
I have the same issue here @AidaRvi  @AlexJohnSadowski

**Comment by rasmus-rudling** [comment]
I have the same issue, any solutions @AidaRvi @reda-xk7 @AlexJohnSadowski ?

**Comment by paramsinghvc** [comment]
I did some digging, and found in [processRequest.js](https://github.com/jaydenseric/graphql-upload/blob/e01b5d5541760d529b06c900883c5fa7febcff00/processRequest.mjs#L249) that createReadStream method is being called once before `stream.on('limit',...)` emits an error. So, the thrown error is going no where! 

Not sure what's the solution here or if its an implementation bug? @jaydenseric 

<img width="534" alt="Screenshot 2023-05-10 at 10 40 53" src="https://github.com/jaydenseric/graphql-upload/assets/4329912/5252a0d8-aed9-4c52-b0bc-caa10417b246">
<img width="493" alt="Screenshot 2023-05-10 at 10 41 10" src="https://github.com/jaydenseric/graphql-upload/assets/4329912/93a95c4c-45dd-4efa-bde4-65855eef864e">

**Comment by IvanSereginGitHub** [comment]
What I did is just this:
`    stream.on('error', (err) => {
        console.error(err.message);
    });
`
and it just catches that error.
