### ISSUE TITLE
Max File Size not working for apollo-server-lambda

### ISSUE THREAD

**Issue by yevhenii-kas-oppizi** [jaydenseric/graphql-upload#302]
I'm using apollo-server-lambda for server and uploading data, but I can not set Max File size and always get nest error 
![CleanShot 2022-05-11 at 19 14 13](https://user-images.githubusercontent.com/93513279/167897717-a97faa6b-13d7-43fe-a8d0-fb254f207c20.png)
Can I resolve this problem, and how?

Here is my code:
```javascript
import { ApolloServer } from "apollo-server-lambda";
import Express, { Application } from "express";
import { graphqlUploadExpress } from "graphql-upload";
import { resolvers } from "./graphql/resolvers";
import { typeDefs } from "./graphql/schema";

const server = new ApolloServer({
  typeDefs,
  resolvers,
  introspection: process.env.NODE_ENV !== "production",
});

export const handler = server.createHandler({
  expressAppFromMiddleware(middleware) {
    const app: Application = Express();
    app.use(graphqlUploadExpress({ maxFileSize: 100000000, maxFiles: 10 }));
    app.use(middleware);
    return app;
  },
  expressGetMiddlewareOptions: {
    cors: {
      origin: "*",
      credentials: true,
    },
    bodyParserConfig: { limit: "100mb" },
  },
});

**Comment by jaydenseric** [comment]
I can't speak for how to configure `apollo-server-lambda` or AWS Lambda regarding request size limits and things, but you need to make sure that your server infrastructure has larger limits set that the limits set in `graphql-upload`, otherwise the error won't be a nice one that `graphql-upload` produces.
