### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by PiTiLeZarD** [jaydenseric/graphql-upload#307]
Hi,

I just tried to use this library and get this error:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /path/to/my/app/node_modules/graphql-upload/package.json
```

I've tried removing node_modules and reinstall it all, same same.

**Comment by jaydenseric** [comment]
Duplicates https://github.com/jaydenseric/graphql-upload/issues/305 .

You can see an explanation here:

https://github.com/jaydenseric/graphql-upload/issues/305#issuecomment-1134736158

**Comment by PiTiLeZarD** [comment]
Thanks for answering that fast, and thanks for all your work on these libraries.

If I may: I'm sure the choice is justified but as it's unconventional, it would benefit with a mention related to that effect in the main readme. 

Changelogs are only important for people who follow all versions, I never used that library and started today, so I had no incentive to find answers in the changelog.

Either way thanks for the answer, I'll have another crack at this!
