### ISSUE TITLE
Main is required in package.json, but it was removed

### ISSUE THREAD

**Issue by Valeronlol** [jaydenseric/graphql-upload#313]
https://github.com/jaydenseric/graphql-upload/commit/1bcd630499a7b14462bb2329a4b2207fba432d84

Error:
No "exports" main defined in ../node_modules/graphql-upload/package.json
    at new NodeError (node:internal/errors:377:5)
    ...

**Comment by jaydenseric** [comment]
Duplicates https://github.com/jaydenseric/graphql-upload/issues/305, see https://github.com/jaydenseric/graphql-upload/issues/305#issuecomment-1134736158 .
