### ISSUE TITLE
Cannot find module 'graphql-upload' or its corresponding type declarations

### ISSUE THREAD

**Issue by kaihaase** [jaydenseric/graphql-upload#319]
Since version 14.0.0 the error message "Cannot find module 'graphql-upload' or its corresponding type declarations" occurs in my TypeScript Project (https://github.com/lenneTech/nest-server). With version 13.0.0 everything runs without problems. Do I need to install additional packages or change anything in the TypeScript configuration?

**Comment by jaydenseric** [comment]
These changes are documented in the changelog and and GitHub release descriptions, and are discussed in multiple past issues, but here is what you need to do to get going:

https://github.com/lenneTech/nest-server/blob/c95c6c243b45af462947102b0f66200ea6b1d487/src/server/modules/file/file.resolver.ts#L3

```diff
- import { FileUpload, GraphQLUpload } from 'graphql-upload';
+ import GraphQLUpload from 'graphql-upload/GraphQLUpload.js';
+ import type { FileUpload } from 'graphql-upload/processRequest.js';
```

https://github.com/lenneTech/nest-server/blob/c95c6c243b45af462947102b0f66200ea6b1d487/src/core.module.ts#L7

```diff
- import { graphqlUploadExpress } from 'graphql-upload';
+ import graphqlUploadExpress from 'graphql-upload/graphqlUploadExpress.js';
```

Make sure your TypeScript config has:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "maxNodeModuleJsDepth": 10,
    "module": "nodenext"
  }
}
```

**Comment by kaihaase** [comment]
@jaydenseric Thank you very much for your quick support. I have left the TypeScript configuration module in the project on `commonjs`, because otherwise there are problems with other packages. Your hints about the imports helped me a lot though.

**Comment by xerstom** [comment]
Hi @jaydenseric ! 
Is there a way to make it work without having to use `"module": "nodenext"` ?

**Comment by jaydenseric** [comment]
@xerstom if you are importing modern ESM packages in a Node.js project, it's expected and reasonable that you have to configure TypeScript to resolve imports the modern Node.js way. You question is more a general usage/config question about TypeScript that is better asked in a TypeScript community space.

You might be able to use `"module": "node16"` if your project is not using top level `await`. You also might be able to do something different with `module` if you set [`moduleResolution`](https://www.typescriptlang.org/docs/handbook/module-resolution.html) to `node16` or `nodenext`, but I'm not sure it's a good idea or will work.

**Comment by lukmagg** [comment]
I still have the error

import GraphQLUpload from 'graphql-upload/GraphQLUpload.js';


Cannot find module 'graphql-upload/GraphQLUpload.js' or its corresponding type declarations.

**Comment by andranikkk** [comment]
did you do something with that?
