### ISSUE TITLE
Cant require Upload and graphqlUploadExpress

### ISSUE THREAD

**Issue by TolgaYld** [jaydenseric/graphql-upload#324]
Hi,

firstly sorry i think it will be a duplicate but i cant fix the error.

this was my old "import"
`const { graphqlUploadExpress, Upload } = require('graphql-upload');`

now i write:

```
const Upload = require('graphql-upload/Upload');
const graphqlUploadExpress = require('graphql-upload/graphqlUploadExpress');
```

and i still get this error:

"Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './Upload' is not defined by "exports" in /Users/user/Desktop/App/dummys/node/project/node_modules/graphql-upload/package.json"

How can i fix this?

thanks in advance :)

**Comment by jaydenseric** [comment]
You need to specify the full file name with the file extension:

```js
const graphqlUploadExpress = require("graphql-upload/graphqlUploadExpress.js");
```

I'm not sure why you want to require the `Upload` class, as that is more of an implementation detail. If you want to get the TypeScript type for what the `Upload` scalar resolves, you can do it this way for JSDoc based types:

```js
/** @type {import("graphql-upload/processRequest.js").FileUpload} */
```

Or this way in TypeScript (assuming you have the right TypeScript project config):

```ts
import type { FileUpload } from "graphql-upload/processRequest.js";
```

Hope that helps!

**Comment by ZobairQ** [comment]
this is still an issue.. even with `const graphqlUploadExpress = require("graphql-upload/graphqlUploadExpress.js");` it is not working

**Comment by Miguel-Leite** [comment]
I'm having problems using graphql-upload. Does anyone have the solution?

**Comment by sebastianFast** [comment]
const { graphqlUploadExpress } = require("graphql-upload");

Worked yesterday and today it doesnt;

No "exports" main defined in ....

**Comment by owali-softic** [comment]
const { graphqlUploadExpress } = require("graphql-upload");

cannot find this, there is conflict with     "express-graphql": "^0.12.0",
    "graphql": "^15.8.0", version. How can I solve this

**Comment by great-ian** [comment]
It seems still not worked.
Any Ideas? 
(  "graphql-upload": "^13.0.0",) 

Error message : Package subpath './graphqlUploadExpress.js' is not defined by "exports" in

**Comment by Maxcrazy1** [comment]
Error: Package subpath './graphqlUploadExpress' is not defined by "exports".

This buf still exists! 😿😿
