### ISSUE TITLE
[v15.0.2] No "exports" main defined in /.../node_modules/graphql-upload/package.json

### ISSUE THREAD

**Issue by wojtekKrol** [jaydenseric/graphql-upload#325]
Im migrating from apollo v2 to v3 and wanted to update `graphql-upload` and occur this error

```
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/wkrol/vazco/fruitful-insights/server2/node_modules/graphql-upload/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.wrappedResolveFilename [as _resolveFilename] (/home/wkrol/vazco/fruitful-insights/server2/node_modules/newrelic/lib/shimmer.js:364:42)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.wrappedLoad [as _load] (/home/wkrol/vazco/fruitful-insights/server2/node_modules/newrelic/lib/shimmer.js:373:24)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
![image](https://user-images.githubusercontent.com/64773541/176437733-7e621053-ee63-48b0-9d10-0c482ac8eec9.png)

My packages are:
```
   "graphql-upload": "15.0.2",
    "@types/graphql-upload": "8.0.11",
```
![image](https://user-images.githubusercontent.com/64773541/176437345-fed4fdd3-d6c0-4a52-b340-fcd50308a084.png)

[I saw this thread](https://github.com/jaydenseric/graphql-upload/issues/305) but these solutions do not work for me, could someone tell me how to make it work?

**Comment by wojtekKrol** [comment]
@jaydenseric I've removed it from `package.json` and then run `npm ci`. Error remains 
![image](https://user-images.githubusercontent.com/64773541/176440807-37c02f92-1d74-4666-a54c-c4febab1d051.png)

**Comment by jaydenseric** [comment]
Does you project TypeScript config have `compilerOptions.module` set to `nodenext`?

**Comment by jaydenseric** [comment]
It should be set to `nodenext` (or `node16` if you want to forbid top level `await`) so TypeScript resolves imports and types the modern Node.js way. Also make sure your TypeScript version (both used via CLI, and the one powering VS Code intellisense) is up to date as only recent versions of TypeScript support that mode and appropriately make use of the `package.json` `exports` field and such.

**Comment by jaydenseric** [comment]
I just realise in your screenshot [here](https://github.com/jaydenseric/graphql-upload/issues/325#issuecomment-1169943243) that you're not specifying the full file name with extension in the import path. You were doing so correctly in the first screenshot but not the second.

**Comment by wojtekKrol** [comment]
Still nothing 
![image](https://user-images.githubusercontent.com/64773541/176457089-5ddd6fe4-fe10-424a-9937-04bb5eeeedc9.png)
FYI @jaydenseric

**Comment by jaydenseric** [comment]
@wojtekKrol there are several things wrong at once in that screenshot. Firstly, it looks in the bottom left like your TypeScript version is out of date because it's failing to recognise the `node16` value. Another thing wrong is you are trying to import something that doesn't exist; use:

```ts
import type { FileUpload } from "graphql-upload/processRequest.js";
```

Another problem you can see in the bottom right is you are attempting to use Node.js to run ESM without using the correct `.mjs` file extension, as the error message says.

**Comment by jaydenseric** [comment]
Without looking at the other settings, `"moduleResolution": "node"` is wrong; it's overriding the behavior of `"module": "node16"`. Try deleting it.
