### ISSUE TITLE
[Bug] Missing "." export in "graphql-upload" package

### ISSUE THREAD

**Issue by harrytran998** [jaydenseric/graphql-upload#326]
Hi @jaydenseric, thanks for your great lib. But today when I updated the latest lib --> I had a problem with this issue.  I hope you can export all with '.'  😆.

**Comment by jaydenseric** [comment]
Hi, thanks for the kind words :)

Please refer to this comment here:

https://github.com/jaydenseric/graphql-upload/issues/327#issuecomment-1193414459

**Comment by koresar** [comment]
@harrytran998 
I will keep [my fork](https://github.com/flash-oss/graphql-upload-minimal) of graph-upload as CJS compatible forever.
