### ISSUE TITLE
Issues importing modules

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [jaydenseric/graphql-upload#334]
My original issues had to do with #332 and #333 , which led me to the same problem as this comment https://github.com/jaydenseric/graphql-upload/issues/332#issuecomment-1216789254 .

I think I've read through all of the related issues associated with the changes to this library. I've made the changes as suggested in the README and it also doesn't seem to help. 

I'm running into the following error when I try to use the new import:

`Must use import to load ES Module: /<PATH>/src/backend/node_modules/graphql-upload/graphqlUploadExpress.mjs`

The code is as follows for the import:

```ts
import { graphqlUploadExpress } from "graphql-upload/graphqlUploadExpress.mjs";
```

I've got the following compiler options in `tsconfig.json`

```json
"compilerOptions": {
    "module": "Node16",
    "maxNodeModuleJsDepth": 10,
    "allowJs": true,
  },
```

and am running the app using `npx nodemon`

I'm not really sure what else to try. Any advice for any other things to try?

**Comment by jaydenseric** [comment]
Hi @Nathan-Nesbitt , the right way to do that import is like this:

```js
import graphqlUploadExpress from "graphql-upload/graphqlUploadExpress.mjs";
```

As you can see the export is s default export:

https://github.com/jaydenseric/graphql-upload/blob/e01b5d5541760d529b06c900883c5fa7febcff00/graphqlUploadExpress.mjs#L34

Hope that helps!

**Comment by Nathan-Nesbitt** [comment]
@jaydenseric thanks for the quick response, thought this had fixed the original issue but I seem to be back at this again.

`Must use import to load ES Module: /<PATH>/backend/node_modules/graphql-upload/graphqlUploadExpress.mjs`or the VS warning `Module 'graphql-upload/graphqlUploadExpress.mjs' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.`

**Comment by jaydenseric** [comment]
Most likely you are not really writing ESM; you have some sort of dev tooling that transpiles the source ESM you're writing to CJS that actually runs at runtime. In Node.js, ESM can import from ESM or CJS modules, but CJS can't require an ESM module. This is not an issue with `graphql-upload`, but rather how Node.js works and your project is setup.

I highly, highly, recommend using ESM in projects both in the source code and at runtime. Your best solution in the long term is to change your build tooling to emit ESM for the runtime code, or else you will get locked out of more and more npm packages over time as they all migrate to pure ESM.

**Comment by yalcinhayyam** [comment]
I have same issue


C:\Users\*\Desktop\*\node_modules\graphql-upload\GraphQLUpload.mjs:3
import { GraphQLError, GraphQLScalarType } from "graphql";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Module._compile (C:\Users\*\Desktop\*\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.newLoader [as .mjs] (C:\Users\*\Desktop\*\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
