### ISSUE TITLE
Error - No "exports" main defined

### ISSUE THREAD

**Issue by CamiloGPT** [jaydenseric/graphql-upload#337]
Hi

I'm using:
Node.js v18.0.0
Graphql-upload 16.0.2
Express 4.18.1
Only JavaScript

```javascript
const { graphqlUploadExpress } = require("graphql-upload"); 
```

And show this Error:

```
node:internal/modules/cjs/loader:489
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /node_modules/graphql-upload/package.json
```

Command audit:

```
npm audit
found 0 vulnerabilities
```

I already executed these commands, but they do not solve anything:

```
# 👇️ delete node_modules and package-lock.json
rm -rf node_modules
rm -f package-lock.json
rm -f yarn.lock

# 👇️ clean npm cache
npm cache clean --force

npm install
```

### how do I fix this error?
Thanks

**Comment by jaydenseric** [comment]
Please see the “Exports” section of the readme:

https://github.com/jaydenseric/graphql-upload#exports

The correct way is:

```js
import graphqlUploadExpress.mjs from "graphql-upload/graphqlUploadExpress.mjs";
```

Note that it's an ESM module, so you can't `require` it from a CJS module in your project but you can `import` it from an ESM module. That's just how Node.js ESM/CJS compatibility works:

https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#interoperability-with-commonjs

**Comment by Luchanso** [comment]
workaround solution for me: 13.0.0v

**Comment by ShilpaM007** [comment]
inorder to use Import, i will have to update module to commonjs, and this would make all of my code where i am using require go on toss. 

Is there anyother way for same

**Comment by jaydenseric** [comment]
@ShilpaM007 

> inorder to use Import, i will have to update module to commonjs

I think you mean the opposite; you will have to update your modules to ESM.

You can import somewhere in a CJS module if it's a dynamic import:

```js
const { default: graphqlUploadExpress } = await import("graphql-upload/graphqlUploadExpress.mjs");
```

Just not a regular import:

```js
import graphqlUploadExpress from "graphql-upload/graphqlUploadExpress.mjs";
```

Note that CJS modules don't support top level `await`, so you will have to either chain a `.then()` or call an async function that contains the awaited dynamic import.

**Comment by yangli-io** [comment]
I'm using typescript and this mjs stuff has just made it super hard to use. I have to do stuff like allowJS which I strictly avoided before to ensure typescript was being used. Still I'm not able to get this to work

**Comment by stanyq4** [comment]
Same here, been trying to upgrade to the LTS node "18.12.1" using Typescript, but this became a blocker. 

@jaydenseric anything you can recommend for TS?

**Comment by codelover2k** [comment]
non of these solution work, also using node 18.12.1
is there no way to offer a default export that works?

**Comment by clintonb** [comment]
https://github.com/meabed/graphql-upload-ts seems to be a suitable replacement.

**Comment by Luchanso** [comment]
GraphQL not about FileUploading or binary transfer data, so the best solution using other methods for uploading, one of: using apart HTTP endpoint for uploading like `example.com/upload` and handle it with your framework express, fastify, etc. with `app.use('/upload', (req, res) => { ... ` and you don't need this package in fact

P.S. this is just my experience and subjective opinion
