### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by productdevbook** [jaydenseric/graphql-upload#353]
import { processRequest } from 'graphql-upload'

```

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in 
/home/productdevbook/Documents/aa/server-micro-library/node_modules/graphql-upload/package.json
 imported from /home/productdevbook/Documents/aa/server-micro-library/src/index.ts

```

**Comment by jaydenseric** [comment]
This duplicates many past issues, please search them and you will be able to figure out what's going on pretty quick.

**Comment by productdevbook** [comment]
https://github.com/jaydenseric/graphql-upload/issues/337#issuecomment-1240038750


```
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/index.js",
      "import": "./dist/index.mjs"
    }
  },
  ```
  
I think you should make an index like this and export funcs from there. Because this is not a good use for some reason.
