### ISSUE TITLE
How can I upload file on Next.js

### ISSUE THREAD

**Issue by SatoshiKawabata** [jaydenseric/graphql-upload#364]
I'm using Next.js and I'd like to upload image file. But my implementation does not works well. How can I do?

I imitated the following implementation, but it does not work well.
https://github.com/jaydenseric/graphql-upload/issues/216#issuecomment-1146063052

My code is here. I'm using these modules:`"@apollo/server": "^4.3.3",`, `"apollo-upload-client": "^17.0.0",`, `"graphql-upload": "^15.0.2",`, `"@as-integrations/next": "^1.2.0",`.

```
import { startServerAndCreateNextHandler } from '@as-integrations/next';
import processRequest from 'graphql-upload/processRequest.js';

export default startServerAndCreateNextHandler(apolloServer, {
  context: async (req, res) => {
    const contentType = req.headers['content-type'];
    if (contentType && contentType.startsWith('multipart/form-data')) {
      req.body = await processRequest(req, res);
    }
    return {
      token: await getTokenFromReq(req),
    };
  },
});
```

I got this error.

```
{"errors":[{"message":"Context creation failed: Unexpected end of form","extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["Error: Unexpected end of form","    at Multipart._final (/node_modules/busboy/lib/types/multipart.js:588:17)","    at callFinal (node:internal/streams/writable:694:27)","    at prefinish (node:internal/streams/writable:723:7)","    at finishMaybe (node:internal/streams/writable:733:5)","    at Multipart.Writable.end (node:internal/streams/writable:631:5)","    at onend (node:internal/streams/readable:693:10)","    at processTicksAndRejections (node:internal/process/task_queues:78:11)"]}}]}

```

**Comment by jaydenseric** [comment]
Hi @SatoshiKawabata , if I knew of the top of my head the exact code to share for that I would, but alas, I do not. I keep my GraphQL APIs seperate from my Next.js app projects. If you figure it out, feel free to share your answer here in case it helps someone else!
