### ISSUE TITLE
Apollo Server v4 with Lambda

### ISSUE THREAD

**Issue by danieljarrett74** [jaydenseric/graphql-upload#365]
Greetings from a fellow Melbournian. 

This isn't an issue so much as a question.  And I know it's been asked previously but I don't think it's been asked since Apollo Server v4. 

I noticed you have added examples for v4 and koa here https://github.com/jaydenseric/apollo-upload-examples/commit/a5da903448e31abaf718be6a21d13d253fc3983b

I'm wondering if there's any update on Lambda support (v4 or even v3)

**Comment by jaydenseric** [comment]
Hi :)

No, there is nothing to new to report about Lambda support. You can subscribe to https://github.com/jaydenseric/graphql-upload/issues/155 to stay up to date about that. This is a good comment to read: https://github.com/jaydenseric/graphql-upload/issues/155#issuecomment-632998596 .
