### ISSUE TITLE
ERROR [ExceptionsHandler] Multipart: Boundary not found - Digital Ocean - AppPlatform 

### ISSUE THREAD

**Issue by SebaBoler** [jaydenseric/graphql-upload#366]
Hello everyone,

my stack : NestJs + Graphql Apollo + graphql-upload
I didn't update any package and after a few days upload starts when i try to upload any file I have issue 

```
ERROR [ExceptionsHandler] Multipart: Boundary not found
```

In the Local environment, it works perfectly.
Does anyone have the same problem?

**Comment by jaydenseric** [comment]
Closing because this isn't an actionable issue I can solve in this project, but if anyone has some tips about a similar problem they experienced with that particular setup (DigitalOcean App Platform, NestJS, Apollo) feel free to share.
