### ISSUE TITLE
FileUpload - where is fileName, mimetype and createReadStream ?

### ISSUE THREAD

**Issue by SebaBoler** [jaydenseric/graphql-upload#367]
I have migrated to the new version from 13 to 16.0.2
But have issue about FileUpload TS2304: Cannot find name 'FileUpload'.

I need to change to Upload ?

I didn't find anything about conversion from FileUpload to Upload in documentation

**Comment by SebaBoler** [comment]
Didnt find any good documentation to migration process from 13 to 16

in entity if you use FileUpload now you will use the same from import FileUpload from 'graphql-upload/Upload.mjs';

**Comment by jaydenseric** [comment]
> Didnt find any good documentation to migration process from 13 to 16

Not sure why you would say this when the [changelog](https://github.com/jaydenseric/graphql-upload/blob/master/changelog.md) entries for each major version explains the breaking changes, and specifically has code examples for how to migrate the import paths, e.g:

<img width="1080" alt="Screenshot 2023-03-23 at 8 26 56 am" src="https://user-images.githubusercontent.com/1754873/227042463-c91d1296-dd76-4f78-88d3-7a98e727873a.png">

You can also see the same changelog content in the GitHub release descriptions:

https://github.com/jaydenseric/graphql-upload/releases

> But if you have like me const { fileName, mimetype, createReadStream } = file will not work and didn't find any docs

This is not worded well. Docs for what exactly? How to use the upload scalar in resolvers? That is documented:

https://github.com/jaydenseric/graphql-upload/blob/e01b5d5541760d529b06c900883c5fa7febcff00/GraphQLUpload.mjs#L53

And there is a working example of this:

https://github.com/jaydenseric/apollo-upload-examples/blob/a5da903448e31abaf718be6a21d13d253fc3983b/api/storeUpload.mjs#L17

You need to `await` the file upload promise to be able to access the data.

**Comment by nicostubi** [comment]
Thank you.

I've tried both:

```
const GraphQLUpload_mjs_1 = require("graphql-upload/GraphQLUpload.mjs");
                            ^
Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/node_modules/graphql-upload/GraphQLUpload.mjs not supported.
```
