### ISSUE TITLE
Hard to find FileUpload interface.

### ISSUE THREAD

**Issue by NivSv** [jaydenseric/graphql-upload#369]
I have tried to use 'graphql-upload' today and I couldn't find the `FileUpload` interface for a while I only realized that I could take it from the `graphql-upload/Upload.mjs` file after I check the types of the package aka `@types/graphql-upload` so I figured I might make it easier for the next person and add it to the readmefile and fix that comment in `GraphQLUpload.mjs` file in line 69 from `import type { FileUpload } from "graphql-upload/processRequest.mjs";` to `* import { FileUpload } from 'graphql-upload/Upload.mjs';` which worked for me

**Comment by jaydenseric** [comment]
See https://github.com/jaydenseric/graphql-upload/pull/370#pullrequestreview-1399597676 .
