### ISSUE TITLE
export graphqlUploadExpress

### ISSUE THREAD

**Issue by kamalkech** [jaydenseric/graphql-upload#374]
"graphql-upload": "^16.0.2",
"@types/graphql-upload": "^16.0.0",

import { graphqlUploadExpress } from 'graphql-upload';

Module '"graphql-upload"' has no exported member 'graphqlUploadExpress'

![image](https://github.com/jaydenseric/graphql-upload/assets/1313428/9e67ae3d-cae2-47b2-822e-714da26b664f)

**Comment by jaydenseric** [comment]
What makes you think you should be able to import like that?

**Comment by kamalkech** [comment]
because before i using old version / 16.0.0 and it s work, the idea is in nestjs app i want to enable upload file + graphql

**Comment by jaydenseric** [comment]
Firstly, if you were using an old version, and you update major versions, look at the release notes about the breaking changes:

https://github.com/jaydenseric/graphql-upload/releases

Changes to exports are documented there.

The current exports are documented here:

https://github.com/jaydenseric/graphql-upload#exports

And release notes and documentation aside, you can just look at the exports and see what can be imported:

- https://unpkg.com/browse/graphql-upload@16.0.2/package.json
- https://unpkg.com/browse/graphql-upload@16.0.2/

**Comment by kamalkech** [comment]
yes i already check the documentation, so i need to check again how can implement this with graphql and nestjs, but current i need to downgrand to old version

**Comment by bnussman** [comment]
@jaydenseric completely messed up this package because of his made up "optimal JavaScript module design". This package is completely broken for Typescript users and nobody is speaking up about it.
