### ISSUE TITLE
in my mutation i have two arguments which have Upload type and both return null 

### ISSUE THREAD

**Issue by ahmedshahd** [jaydenseric/graphql-upload#377]
type Mutation {
  createWellnessTip(
    createWellnessTipInput: CreateWellnessTipInput!
    attachment: [Upload]
    image: Upload
  ): WellnessTip! 
  }
  
  When attempting to upload both an attachment and an image in the same mutation using graphql-upload, the attachment and image fields in the resolver are received as null. This issue doesn't occur when uploading either attachment or image alone.
  
   when i log the attachment and image in resolver i got their value in null 
  image null
attachment [ null, null, null, null ]

i am using   "graphql-upload": "11.0.0",

![Screenshot from 2023-08-16 13-08-56](https://github.com/jaydenseric/graphql-upload/assets/48631752/584484b9-0919-42c7-9401-03f45c67cac4)
![Screenshot from 2023-08-16 13-09-11](https://github.com/jaydenseric/graphql-upload/assets/48631752/ff151887-4254-4228-9f56-d7a9b0d94f7e)
![Screenshot from 2023-08-16 13-09-23](https://github.com/jaydenseric/graphql-upload/assets/48631752/e12c7464-7454-4461-9984-f77c011d7c4d)
![Screenshot from 2023-08-16 13-09-40](https://github.com/jaydenseric/graphql-upload/assets/48631752/5cc0dc79-727d-4a04-9e77-cab17c5549d5)

**Comment by jaydenseric** [comment]
Sorry, but I don't have availability to help people debug their project code. I can only accept bug reports with minimum reproduction steps for issues that are specific to the `graphql-upload` middleware malfunctioning on the server. It's not clear that your problem relates to that; maybe your client isn't sending a correct [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure) to the server.

**Comment by ahmedshahd** [comment]
Hi jay sorry for the disturbing
I only want to know that is this a valid mutation

type Mutation {
createWellnessTip(
createWellnessTipInput: CreateWellnessTipInput!
attachment: [Upload]
image: Upload
): WellnessTip!
}

Can i have two arguments with upload type

Thanks jay 🙏

**Comment by jaydenseric** [comment]
You can use `Upload` scalar in as many places as you like in mutation arguments; you just need to remember to actually set all the right file values in the variables when you submit a mutation.
