### ISSUE TITLE
multipart fields

### ISSUE THREAD

**Issue by appasaheb4** [jaydenseric/graphql-upload#386]
Facing below issue:
[Nest] 22115  - 05/24/2024, 5:13:37 PM   ERROR [ExceptionsHandler] Misordered multipart fields; files should follow ‘map’ (https://github.com/jaydenseric/graphql-multipart-request-spec).
BadRequestError: Misordered multipart fields; files should follow ‘map’ (https://github.com/jaydenseric/graphql-multipart-request-spec).

**Comment by jaydenseric** [comment]
The error message means the client is not sending the request correctly, as per the error message. This repo is for handling GraphQL multipart requests on the server side. Please investigate why your client is sending invalid requests and fix the problem there.

**Comment by appasaheb4** [comment]
Hi @jaydenseric  thanks for reply.
Issue fixed.
app.use(
    '/graphql',
    graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
  );
  app.use('/api', formData.parse());

**Comment by appasaheb4** [comment]
I handle both grahql with rest api single instace
image upload time facing issue 
I fixed.
thx
