### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by jaydenseric** [jaydenseric/graphql-upload#68]
It is time to drop `apollo` from the name as this package is also useful for non-Apollo GraphQL servers and clients.

Anyone have any tips for renaming a package? I have never done it before and it seems like an inherently disruptive thing to do.

I'm thinking:

* [x] Research and achieve compatibility with other Node.js GraphQL servers, i.e. [`express-graphql`](https://www.npmjs.com/package/express-graphql).
* [ ] Rename this repo in GitHub. GitHub automatically redirects people visiting old URLs.
* [ ] Rename the package in `package.json` and anywhere else the name appears.
* [ ] Publish the the new package.
* [ ] Deprecate the old package, advising to switch to the new package.

I'll think about it for a bit before doing it 😅

**Comment by jaydenseric** [comment]
I've found this package to be compatible with:

- [`graphql-api-koa`](https://npm.im/graphql-api-koa)
- [`express-graphql`](https://npm.im/express-graphql)
- [`apollo-server`](https://npm.im/apollo-server)

**Comment by giautm** [comment]
[`graphql-upload-server`](https://www.npmjs.com/package/graphql-upload-server) <-- This is available npm package name, you could use it. 😄

**Comment by jaydenseric** [comment]
All done 🎉

I just published [`graphql-upload`](https://npm.im/graphql-upload).

[See the changelog for a migration guide](https://github.com/jaydenseric/graphql-upload/blob/master/changelog.md#800).

Here is the deprecation warning everyone sees when attempting to install [`apollo-upload-server`](https://npm.im/apollo-upload-server):

<img width="813" alt="screen shot 2018-09-18 at 3 27 21 pm" src="https://user-images.githubusercontent.com/1754873/45666187-f6163700-bb57-11e8-91a7-da1df1494286.png">

The Github short URL links to this issue.

**Comment by jaydenseric** [comment]
Really happy with the change, it looks so clean and logical everywhere now 😍

<img width="421" alt="screen shot 2018-09-18 at 4 07 25 pm" src="https://user-images.githubusercontent.com/1754873/45667605-31ffcb00-bb5d-11e8-88ae-982b1680a151.png">

<img width="498" alt="screen shot 2018-09-18 at 4 06 33 pm" src="https://user-images.githubusercontent.com/1754873/45667610-34622500-bb5d-11e8-92d6-89c4ee67506c.png">
